/** Pure, deterministic educational numerics. No model downloads or biological predictions. */
export function random(seed=42){let s=seed>>>0;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}}
export const sigmoid=(x:number)=>1/(1+Math.exp(-Math.max(-60,Math.min(60,x))));
export function softmax(xs:number[]){const m=Math.max(...xs);const es=xs.map(x=>Math.exp(x-m));const sum=es.reduce((a,b)=>a+b,0);return es.map(x=>x/sum)}
export type Point={x:number[];y:number};
export type Net={w:number[][];b:number[];v:number[];c:number;a:number[];u:number[]};
export type TrainOptions={model:'linear'|'mlp'|'transfer';dataset:'linear'|'xor'|'circle';epochs:number;rate:number;strategy:'frozen'|'full'|'lora'};
export function data(kind:string,n:number,seed:number):Point[]{const rng=random(seed);return Array.from({length:n},()=>{const x=[rng()*2-1,rng()*2-1];return{x,y:Number(kind==='linear'?x[0]+.6*x[1]>0:kind==='circle'?x[0]**2+x[1]**2<.45:x[0]*x[1]<0)}})}
export function network(seed=19):Net{const r=random(seed);return{w:Array.from({length:6},()=>[r()*2-1,r()*2-1]),b:Array.from({length:6},()=>r()-.5),v:Array.from({length:6},()=>r()-.5),c:0,a:[.1,-.1],u:Array(6).fill(0)}}
export function forward(n:Net,x:number[],linear=false,lora=false){const h=linear?x:n.w.map((w,j)=>Math.tanh(w[0]*x[0]+w[1]*x[1]+n.b[j]+(lora?n.u[j]*(n.a[0]*x[0]+n.a[1]*x[1]):0)));return{h,p:sigmoid(h.reduce((s,v,j)=>s+v*n.v[j],n.c))}}
function metrics(n:Net,ds:Point[],linear:boolean,lora:boolean){let loss=0,correct=0;for(const d of ds){const p=forward(n,d.x,linear,lora).p;loss-=d.y*Math.log(Math.max(p,1e-12))+(1-d.y)*Math.log(Math.max(1-p,1e-12));correct+=Number(Number(p>=.5)===d.y)}return{loss:loss/ds.length,accuracy:correct/ds.length}}
export function step(n:Net,ds:Point[],rate:number,linear:boolean,strategy:string){const gv=Array(linear?2:6).fill(0),gw=Array.from({length:6},()=>[0,0]),gb=Array(6).fill(0),gu=Array(6).fill(0),ga=[0,0];let gc=0;for(const d of ds){const {h,p}=forward(n,d.x,linear,strategy==='lora'),delta=p-d.y;gc+=delta;h.forEach((v,j)=>{gv[j]+=delta*v;if(!linear){const g=delta*n.v[j]*(1-v*v);gb[j]+=g;for(let k=0;k<2;k++){gw[j][k]+=g*d.x[k];ga[k]+=g*n.u[j]*d.x[k]}gu[j]+=g*(n.a[0]*d.x[0]+n.a[1]*d.x[1])}})}const scale=rate/ds.length;n.c-=scale*gc;gv.forEach((g,j)=>n.v[j]-=scale*g);if(!linear&&strategy==='full')for(let j=0;j<6;j++){n.b[j]-=scale*gb[j];for(let k=0;k<2;k++)n.w[j][k]-=scale*gw[j][k]}if(!linear&&strategy==='lora'){for(let j=0;j<6;j++)n.u[j]-=scale*gu[j];for(let k=0;k<2;k++)n.a[k]-=scale*ga[k]}}
export function train(o:TrainOptions){const linear=o.model==='linear';const ds=data(o.dataset,100,42),val=data(o.dataset,60,314);const n=network();if(linear)n.v=[0,0];if(o.model==='transfer'){const pre=data('linear',100,81);for(let e=0;e<180;e++)step(n,pre,.35,false,'full');n.v=network(77).v;n.c=0}const initial=JSON.parse(JSON.stringify(n)) as Net;const strategy=o.model==='transfer'?o.strategy:'full';const history:{epoch:number;loss:number;valLoss:number;accuracy:number;valAccuracy:number;net:Net}[]=[];const record=(epoch:number)=>{const m=metrics(n,ds,linear,strategy==='lora'),v=metrics(n,val,linear,strategy==='lora');history.push({epoch,loss:m.loss,valLoss:v.loss,accuracy:m.accuracy,valAccuracy:v.accuracy,net:JSON.parse(JSON.stringify(n)) as Net})};record(0);for(let e=1;e<=o.epochs;e++){step(n,ds,o.rate,linear,strategy);if(e%5===0||e===o.epochs)record(e)}return{kind:'educational-training',seed:42,trainCount:100,validationCount:60,pretrainingEpochs:o.model==='transfer'?180:0,trainable:linear?3:o.model==='transfer'?(strategy==='frozen'?7:strategy==='lora'?15:25):25,initial,points:ds,history,final:history[history.length-1]}}
export function attention(tokens:string[],head:number,causal:boolean){const X=tokens.map((t,i)=>Array.from({length:4},(_,k)=>Math.sin((t.charCodeAt(0)+k*13)*.17)+Math.sin(i/Math.pow(10000,k/4))));const project=(offset:number)=>X.map(x=>Array.from({length:4},(_,j)=>x.reduce((s,v,k)=>s+v*Math.sin((k+1)*(j+1)+(head+1)*offset)*.6,0)));const Q=project(1),K=project(2),V=project(3);const scores=Q.map((q,i)=>K.map((k,j)=>causal&&j>i?-Infinity:q.reduce((s,v,d)=>s+v*k[d],0)/2));const weights=scores.map(softmax);const output=weights.map(row=>Array.from({length:4},(_,d)=>row.reduce((s,w,j)=>s+w*V[j][d],0)));return{tokens,X,Q,K,V,scores:scores.map(row=>row.map(x=>Number.isFinite(x)?x:null)),weights,output,dk:4,head,causal}}
export const corpus=['the protein is soluble','the protein is stable','the protein is soluble','the enzyme binds a substrate','the enzyme is stable','a protein has a sequence','a sequence contains amino acids','the model learns a sequence','the model predicts a token','the protein binds a molecule','the enzyme is soluble','a model learns from data'];
export function language(prompt:string,mode:'next'|'masked',temperature:number){const tokens:string[]=prompt.toLowerCase().match(/\[mask\]|[a-z]+/g)||[];const vocab=Array.from(new Set(corpus.flatMap(x=>x.split(' ')))).sort();const counts=Object.fromEntries(vocab.map(t=>[t,0]));const pos=tokens.indexOf('[mask]');const previous=mode==='next'?tokens[tokens.length-1]:tokens[pos-1];const next=mode==='masked'?tokens[pos+1]:undefined;let matches=0;for(const line of corpus){const ts=line.split(' ');ts.forEach((t,i)=>{if((previous===undefined||ts[i-1]===previous)&&(next===undefined||ts[i+1]===next)){counts[t]++;matches++}})}if(!matches)for(const line of corpus)for(const t of line.split(' '))counts[t]++;const probabilities=softmax(vocab.map(t=>Math.log(counts[t]+.1)/temperature));return{kind:'count-based-language-demo',mode,temperature,matches,corpusSentences:corpus.length,candidates:vocab.map((token,i)=>({token,probability:probabilities[i],count:counts[token]})).sort((a,b)=>b.probability-a.probability)}}
