// Traducao dos experimentos. Mesma forma do original em content.ts: o que
// falta aqui cai no ingles em vez de sumir da tela.

export const exhibitsPt: Record<string, {title: string; short: string; kicker: string; heading: string; accent: string; description: string}> = {
  map: {
    title: 'O panorama',
    short: 'O panorama',
    kicker: 'Modelos de proteína, desdobrados',
    heading: 'A atenção basta para',
    accent: 'dobrar proteínas.',
    description:
      'Para quem está começando em design de proteínas, e para quem esquece o básico. É o mais perto que chegamos do que a natureza faz em segundos, e o que a natureza faz continua sendo o segredo mais bem guardado. Comece pelo mecanismo e depois leia os modelos que o usam.',
  },
  classical: {
    title: 'Aprender com dados',
    short: 'Aprendizado de máquina clássico',
    kicker: '01 / Aprendizado de máquina clássico',
    heading: 'Padrões,',
    accent: 'não instruções.',
    description:
      'Dê exemplos a um modelo e ele aprende uma regra. Mude o problema e veja onde uma fronteira simples funciona e onde ela falha.',
  },
  neuron: {
    title: 'Dentro de um neurônio',
    short: 'O perceptron',
    kicker: '02 / A peça elementar',
    heading: 'Uma decisão',
    accent: 'pequena.',
    description:
      'As entradas carregam informação. Os pesos decidem quanto ela importa. Ajuste os dois e veja um neurônio calcular sua saída.',
  },
  deep: {
    title: 'Quando as camadas aprendem',
    short: 'Aprendizado profundo',
    kicker: '03 / Aprendizado profundo',
    heading: 'Partes simples.',
    accent: 'Padrões complexos.',
    description:
      'Conecte neurônios em camadas e treine seus pesos. Veja uma rede curvar a fronteira de decisão em torno de um problema não linear.',
  },
  language: {
    title: 'Aprender uma língua',
    short: 'Modelos de linguagem e BERT',
    kicker: '04 / Modelos de linguagem',
    heading: 'O sentido',
    accent: 'entre os tokens.',
    description:
      'Um modelo de linguagem aprende padrões estatísticos em sequências. Compare a predição do próximo token com o objetivo mascarado do BERT.',
  },
  attention: {
    title: 'Prestar atenção',
    short: 'Atenção e Transformers',
    kicker: '05 / Atenção e Transformers',
    heading: 'O contexto muda',
    accent: 'tudo.',
    description:
      'Um token não precisa trabalhar sozinho. Veja como consultas, chaves e valores deixam ele trocar informação com o resto da sequência.',
  },
  protein: {
    title: 'A língua da vida',
    short: 'Modelos de linguagem de proteínas',
    kicker: '06 / Modelos de linguagem de proteínas',
    heading: 'Alfabeto novo.',
    accent: 'Ideias conhecidas.',
    description:
      'Troque palavras por aminoácidos. Explore como aprender de sequências de proteína produz representações úteis para a biologia.',
  },
  finetuning: {
    title: 'Do geral ao específico',
    short: 'O laboratório de ajuste fino',
    kicker: '07 / O laboratório de ajuste fino',
    heading: 'Uma tarefa nova.',
    accent: 'Meio caminho já andado.',
    description:
      'Reaproveite o que um modelo já aprendeu e adapte-o a uma tarefa específica. Compare codificador congelado, ajuste fino completo e adaptação de baixo posto.',
  },
};

export const detailsPt: Record<
  string,
  {plain: string; technical: string; biology: string; extra: string[]; question: string; options: string[]; feedback: string}
> = {
  map: {
    plain:
      'Inteligência artificial é o campo amplo. Aprendizado de máquina é uma abordagem dentro dele: aprender padrões a partir de dados em vez de especificar cada regra.',
    technical:
      'Aprendizado profundo é um subconjunto do aprendizado de máquina baseado em redes neurais de várias camadas. Transformers são uma arquitetura; modelagem de linguagem é um objetivo. São categorias relacionadas, não sinônimos.',
    biology:
      'Modelos de linguagem de proteínas aplicam objetivos de aprendizado de sequência a aminoácidos. Nem todo modelo de proteína prevê estrutura em três dimensões, e nem todo modelo de linguagem é um Transformer.',
    extra: [
      'O aprendizado de máquina clássico inclui regressão logística, árvores de decisão, florestas aleatórias e máquinas de vetores de suporte. "Clássico" não quer dizer linear, simples nem obsoleto.',
      'Um modelo de linguagem grande (LLM) é um modelo de linguagem em grande escala; não existe um limiar universal de parâmetros. Um modelo de linguagem de proteínas (pLM) modela sequências de aminoácidos. Aqui pLM sempre significa modelo de linguagem de proteínas, e não simplesmente modelo de linguagem pré-treinado.',
      'Siga as galerias numeradas para uma visita guiada, ou escolha qualquer nó do mapa. Passar o ponteiro, clicar, tocar e chegar pelo teclado revelam a mesma informação. Todos os experimentos rodam modelos pequenos e didáticos, não modelos de fundação hospedados.',
    ],
    question: 'Qual relação está correta?',
    options: ['Aprendizado profundo é um subconjunto do aprendizado de máquina', 'Toda IA é um Transformer', 'Todo pLM prevê estrutura em 3D'],
    feedback:
      'O aprendizado profundo faz parte do aprendizado de máquina. Um Transformer é uma arquitetura neural específica, e prever estrutura de proteína exige um modelo adequado e uma cabeça de saída apropriada.',
  },
  classical: {
    plain:
      'Imagine separar observações em dois grupos. O treino encontra parâmetros que reduzem os erros em exemplos cujos rótulos já são conhecidos.',
    technical:
      'Este experimento ajusta uma regressão logística a duas entradas numéricas com entropia cruzada binária e descida de gradiente em lote. Sua fronteira de probabilidade em 0,5 é uma reta. O XOR exige uma representação não linear.',
    biology:
      'Um modelo clássico de proteína pode usar carga, comprimento ou composição de aminoácidos como atributos. Uma floresta aleatória ou uma SVM com kernel também modelam relações não lineares sem serem uma rede profunda.',
    extra: [
      'Para cada exemplo, calcule uma probabilidade, meça a perda de entropia cruzada contra o rótulo, derive a perda e atualize os pesos. Uma época aqui é uma passagem pelo conjunto de treino inteiro.',
      'A visualização usa 100 pontos sintéticos de treino e 60 pontos de validação gerados de forma independente. Ambos vêm de uma regra escolhida. O mapa de calor mostra a probabilidade de classe prevista; os símbolos mostram os rótulos de treino. A acurácia de validação é separada da perda de treino.',
      'Uma divisão aleatória de proteínas muito parecidas vaza informação de família entre os conjuntos. Em estudos biológicos, considere divisões por identidade de sequência ou por família, um conjunto de teste intocado, desbalanceamento de classes e linhas de base adequadas. Só a acurácia engana.',
      'O zoo abaixo roda nove famílias sobre os mesmos dados, com a mesma fronteira desenhada e a mesma curva de treino. O eixo horizontal muda de significado por família: época, número de árvores, profundidade, k, tamanho da amostra ou iteração.',
    ],
    question: 'Por que a regressão logística tropeça no XOR?',
    options: ['Precisa de mais casas decimais', 'A fronteira dela nesses atributos é linear', 'Ela não tem pesos treináveis'],
    feedback:
      'Os quadrantes opostos do XOR não podem ser separados por uma única reta. Engenharia de atributos ou um modelo não linear mudam isso.',
  },
  neuron: {
    plain:
      'Um neurônio multiplica cada entrada por um peso, soma um viés e aplica uma função de ativação. Um peso pode reforçar uma entrada ou inverter o efeito dela.',
    technical:
      'O perceptron original usa um limiar duro e uma regra de aprendizado guiada por erro. Um neurônio sigmoide é a alternativa diferenciável; não é idêntico ao perceptron histórico.',
    biology:
      'Num classificador simples de proteína, duas entradas poderiam codificar hidrofobicidade normalizada e carga. Os números deste experimento são atributos genéricos, não uma predição biológica validada.',
    extra: [
      'Um peso positivo aumenta z quando a entrada dele aumenta. Um peso negativo diminui z. O viés desloca a resposta mesmo com as duas entradas em zero.',
      'O limiar devolve 1 para z ≥ 0 e 0 caso contrário. A sigmoide leva z para o intervalo (0,1). A ReLU devolve max(0,z), então a saída dela não é uma probabilidade por natureza.',
      'A retropropagação usa a regra da cadeia para calcular derivadas através de operações diferenciáveis. Um degrau duro não serve à retropropagação por gradiente; o perceptron original usa outra regra de atualização.',
    ],
    question: 'O que o viés muda?',
    options: ['O número de entradas', 'O deslocamento da ativação', 'O conjunto de treino'],
    feedback: 'O viés desloca o valor de z antes da ativação, independentemente das entradas atuais, movendo o limiar de decisão.',
  },
  deep: {
    plain:
      'Uma camada transforma as entradas; a seguinte trabalha com os atributos transformados. Ativações não lineares permitem que essas composições representem padrões mais complexos.',
    technical:
      'Este laboratório treina um perceptron de múltiplas camadas 2 → 6 → 1, com ativações tanh na camada oculta e sigmoide na saída. É uma demonstração pequena; modelos profundos atuais têm muito mais camadas.',
    biology:
      'Um modelo profundo de proteína aprende representações de sequência em vez de depender só de descritores desenhados à mão. A arquitetura e o objetivo de treino decidem que informação essas representações guardam.',
    extra: [
      'Passagem direta: calcule ativações ocultas e predições. Perda: compare as predições com os rótulos. Passagem reversa: propague as derivadas da perda até todos os parâmetros treináveis. Atualização: θ ← θ − η∇θL.',
      'Sem ativações não lineares, uma pilha de camadas afins continua sendo um mapeamento afim. Profundidade sozinha não produz fronteira não linear. Este experimento usa tanh justamente para evitar esse colapso.',
      'As curvas vêm de otimização de verdade, no seu navegador. Treino e validação usam exemplos sintéticos diferentes. Perda baixa no treino não estabelece utilidade biológica nem desempenho em famílias de proteína nunca vistas.',
    ],
    question: 'O que acontece se todas as ativações ocultas forem lineares?',
    options: ['A rede vira um Transformer', 'A composição continua afim', 'Ela aprende qualquer fronteira não linear'],
    feedback: 'Compor transformações afins produz outra transformação afim. Ativações não lineares é que permitem representações não lineares.',
  },
  language: {
    plain:
      'A tokenização transforma uma sequência em símbolos discretos. Um embedding leva cada símbolo a um vetor. Um modelo de linguagem aprende a atribuir probabilidades usando o contexto.',
    technical:
      'Modelos autorregressivos preveem o próximo token a partir dos anteriores. O BERT é um codificador que aprende representações bidirecionais com modelagem de linguagem mascarada; o BERT original também usava predição da próxima frase.',
    biology:
      'O BERT é uma ponte útil para a modelagem mascarada de proteínas: esconda parte de uma sequência e preveja o resíduo que falta usando os dois lados. O objetivo transfere, embora tokenização e dados sejam outros.',
    extra: [
      'O BERT-base tem 12 camadas de codificador Transformer, 768 dimensões ocultas e 12 cabeças de atenção, com cerca de 110 milhões de parâmetros. É uma referência introdutória útil, e não um perceptron primitivo nem um modelo de conversa.',
      'No BERT original, 15% das posições de token são escolhidas para o objetivo mascarado. Dessas, 80% viram [MASK], 10% viram um token aleatório e 10% ficam como estão. A perda é calculada nos alvos escolhidos.',
      'As barras de probabilidade usam um corpus minúsculo baseado em contagem. O modo próximo token usa a palavra anterior; o modo mascarado usa as palavras vizinhas à esquerda e à direita quando um contexto casa, e contagens de unigrama caso contrário. Suavização aditiva e temperatura convertem contagens em probabilidades. Isto não é inferência do BERT.',
      'A tokenização de texto aqui separa palavras; o BERT de verdade usa subpalavras WordPiece. Na geração autorregressiva, a temperatura muda a distribuição de saída e a amostragem escolhe o próximo token. Isso é inferência, não atualização de pesos.',
    ],
    question: 'Que contexto o codificador do BERT usa para um token mascarado?',
    options: ['Só os tokens à esquerda', 'Só o próprio token mascarado', 'Tokens dos dois lados'],
    feedback: 'A autoatenção bidirecional usa o contexto à esquerda e à direita. Um decodificador causal bloqueia o acesso às posições futuras.',
  },
  attention: {
    plain:
      'Para cada token, a atenção pergunta quais outros tokens são úteis agora. Ela calcula uma mistura ponderada da informação deles, produzindo uma representação com contexto.',
    technical:
      'Q = XWQ, K = XWK, V = XWV. Os produtos escalares entre consulta e chave são escalados por √dk, mascarados quando for o caso, e normalizados por linha com softmax. Cada linha de pesos soma um.',
    biology:
      'A atenção entre resíduos pode codificar dependências de sequência, inclusive de longo alcance. Um valor de atenção não é automaticamente um contato físico, uma explicação causal nem prova de interação bioquímica.',
    extra: [
      'O mapa de calor usa embeddings de token de 4 dimensões, fixos e não treinados, com informação de posição senoidal. Cada cabeça selecionável usa projeções 4×4 fixas e diferentes. São cálculos exatos de atenção sobre vetores de brinquedo, não pesos extraídos do ESM ou do BERT.',
      'Uma máscara causal coloca menos infinito nas pontuações de posições futuras antes do softmax, zerando a probabilidade delas. Um codificador usa contexto bidirecional; um modelo só de decodificador usa máscara causal.',
      'A atenção de múltiplas cabeças concatena o resultado de cada cabeça e o projeta de volta à dimensão do modelo. Um bloco Transformer também tem uma rede feed-forward por posição, conexões residuais e normalização. Empilhar atenção sozinha não descreve a arquitetura inteira.',
      'O Transformer original é um modelo codificador-decodificador. O BERT usa o desenho do codificador; modelos no estilo GPT usam blocos decodificadores causais. A posição da normalização e o mecanismo posicional variam entre famílias. A atenção densa padrão cria uma matriz n×n de interações por cabeça, com custo quadrático no comprimento da sequência.',
    ],
    question: 'Por que uma linha de atenção soma 1?',
    options: ['O softmax normaliza a linha', 'Todos os tokens têm a mesma importância', 'Ela mede distância física'],
    feedback: 'O softmax deixa as entradas não mascaradas não negativas e normaliza a soma delas em um. Entradas mascaradas ficam com peso zero.',
  },
  protein: {
    plain:
      'Uma sequência de proteína é uma cadeia de aminoácidos, em geral escrita com um alfabeto de 20 letras. Um pLM aprende regularidades estatísticas em muitas sequências assim.',
    technical:
      'pLMs mascarados como o ESM-2 aprendem embeddings contextuais por resíduo. Uma representação pode ser agregada em um vetor por sequência, ou entregue a uma cabeça de predição por resíduo. O ProtT5 faz parte da família ProtTrans.',
    biology:
      'Tarefas possíveis adiante incluem localização, estrutura secundária, estabilidade e predição de função. Representações de sequência são boas entradas, mas a tarefa ainda precisa de rótulos adequados, avaliação e interpretação biológica.',
    extra: [
      'Escolha um resíduo para mascará-lo. O inspetor informa a identidade dele e o agrupamento químico simples; ele não prevê qual aminoácido cabe na posição mascarada. A fração hidrofóbica é um descritor, não uma probabilidade de solubilidade.',
      'O ESM-2 é um modelo de linguagem de proteínas. O ESMFold combina representações do ESM-2 com uma arquitetura de enovelamento para prever estrutura. O modelo de linguagem sozinho não é o preditor de estrutura completo. O ProtTrans reúne vários modelos, entre eles o ProtBERT e o ProtT5.',
      'O embedding de um resíduo é um vetor aprendido, não uma lista nomeada de propriedades físicas. A agregação por média calcula a média dos vetores dos resíduos válidos, excluindo preenchimento e tokens especiais, e perde parte da informação posicional. Para tarefas por resíduo, guarde as representações posição a posição.',
      'O pré-treino aprende de grandes coleções de sequências sem rótulo, por alvos autossupervisionados. Correlações evolutivas ajudam as representações a capturar estrutura e função, mas redundância de sequência, viés de conjunto e sequências fora da distribuição limitam a generalização.',
    ],
    question: 'O ESM-2 sozinho é igual ao ESMFold?',
    options: ['Sim, são intercambiáveis', 'Não, o ESMFold acrescenta uma arquitetura de enovelamento', 'Só para sequências curtas'],
    feedback: 'O ESM-2 fornece representações de sequência aprendidas. O ESMFold acrescenta a maquinaria que as converte em predição de estrutura.',
  },
  finetuning: {
    plain:
      'O pré-treino aprende representações reaproveitáveis. Para resolver a tarefa X, acrescente uma cabeça de saída e treine-a com rótulos da tarefa. Você também pode atualizar parte ou todo o modelo pré-treinado.',
    technical:
      'Uma sonda linear congela o codificador e treina uma cabeça. O ajuste fino completo atualiza os dois. O LoRA congela os pesos originais e aprende mudanças de baixo posto ΔW = BA em matrizes escolhidas.',
    biology:
      'Para predição de solubilidade, um caminho possível é sequência → codificador pré-treinado → embedding agregado → cabeça binária. Use rótulos com base experimental, divisões cientes de família e um conjunto de teste separado antes de interpretar o desempenho.',
    extra: [
      'O experimento roda uma rede minúscula de duas entradas e seis unidades ocultas. Ela aprende primeiro uma tarefa de origem sintética (x₁ + 0,6x₂ > 0), reinicia a cabeça de saída e depois aprende uma tarefa de destino sintética (x₁x₂ < 0). As duas usam coordenadas sintéticas, não proteínas nem rótulos de solubilidade reais.',
      'O modo congelado atualiza sete parâmetros da cabeça de saída. O modo completo atualiza os 25. O modo de baixo posto atualiza os fatores A e B de posto um em torno da matriz 6×2 de pesos de entrada congelada, mais os sete da cabeça: 15 parâmetros treináveis. A escala de baixo posto é um nesta demonstração.',
      'Cada execução reaproveita o mesmo pré-treino de origem e a mesma divisão de destino, então a comparação entre estratégias é controlada. A pontuação de validação mede apenas a tarefa sintética de destino. Modelos maiores, dados reais e outros otimizadores mudam o desempenho relativo.',
      'Para um fluxo real com pLM: remova duplicatas e agrupe sequências; reserve um conjunto de teste intocado; ajuste o pré-processamento só com os dados de treino; escolha taxa de aprendizado e parada pela validação; compare com uma linha de base de descritores e com embeddings congelados; relate incerteza, métricas sensíveis a classe e validação externa quando possível.',
      'Ajuste fino não é prompt, nem geração aumentada por recuperação, nem inferência comum. Ele muda parâmetros treináveis. Treinar um pLM grande exige um ambiente Python com GPU; este site roda de propósito apenas os experimentos pequenos e didáticos.',
    ],
    question: 'O que é atualizado numa sonda linear com codificador congelado?',
    options: ['O codificador pré-treinado inteiro', 'Só a cabeça da tarefa', 'Nenhum parâmetro'],
    feedback:
      'Uma sonda linear treina uma cabeça nova preservando os parâmetros do codificador. O ajuste fino completo e a adaptação de baixo posto mexem em componentes treináveis adicionais.',
  },
};

/** Rotulos da interface dos experimentos. Sao os textos curtos que vivem
 *  dentro dos laboratorios, longe do conteudo editorial. */
export const labPt: Record<string, string> = {
  'The collection': 'A coleção',
  'Learning lab': 'Laboratório',
  Dictionary: 'Dicionário',
  'Your first discoveries': 'Suas primeiras descobertas',
  'Start anywhere. Follow your curiosity.': 'Comece por onde quiser. Siga a curiosidade.',
  'Step inside': 'Entrar',
  'The model catalogue': 'O catálogo de modelos',
  'Architectures, weights and sources': 'Arquiteturas, pesos e fontes',
  'Look deeper: mathematics, methods & limitations': 'Olhar mais fundo: matemática, métodos e limites',
  'Go to the original research': 'Ir à pesquisa original',
  'A guided visit, at your own pace.': 'Uma visita guiada, no seu ritmo.',
  'Back to the collection': 'Voltar à coleção',
  Next: 'Próximo',
  'Knowledge check': 'Teste rápido',
  '01 / The intuition': '01 / A intuição',
  '02 / Under the hood': '02 / Por dentro',
  '03 / The biology connection': '03 / A ligação com a biologia',
  'In plain language': 'Em linguagem simples',
  'The technical idea': 'A ideia técnica',
  'From data to proteins': 'Dos dados às proteínas',
  All: 'Todas',
  'Dictionary category': 'Categoria do dicionário',
  'Try node, perceptron, LoRA, embedding…': 'Tente nó, perceptron, LoRA, embedding…',
  'Search the dictionary': 'Buscar no dicionário',
  'concepts, made approachable': 'conceitos, explicados sem rodeio',
  'Plain language → technical detail → example': 'Linguagem simples → detalhe técnico → exemplo',
  Also: 'Também chamado de',
  'The technical detail': 'O detalhe técnico',
  'For example': 'Por exemplo',
  'See it in action': 'Ver no experimento',
  'No matching term.': 'Nenhum termo corresponde.',
  'Results for': 'Resultados para',
  'No match in': 'Nada em',
  'Showing every category.': 'Mostrando todas as categorias.',
  'Try a shorter word or another category.': 'Tente uma palavra mais curta ou outra categoria.',
  'Clear filters': 'Limpar filtros',
  'Try another word, or clear the filter.': 'Tente outra palavra, ou limpe o filtro.',
  'Live training lab': 'Laboratório ao vivo',
  'Ready to train': 'Pronto para treinar',
  'Train the model': 'Treinar o modelo',
  'Train again': 'Treinar de novo',
  'Computing…': 'Calculando…',
  'Pretrain & adapt': 'Pré-treinar e adaptar',
  'Train a classical classifier': 'Treinar um classificador clássico',
  'Watch a network learn': 'Ver uma rede aprender',
  'The adaptation experiment': 'O experimento de adaptação',
  'Can a line separate it?': 'Uma reta consegue separar?',
  'Give it a hidden layer.': 'Dê a ela uma camada oculta.',
  'Choose what learns.': 'Escolha o que aprende.',
  'Run, pause and inspect each epoch': 'Rode, pause e inspecione cada época',
  'Synthetic dataset': 'Conjunto sintético',
  'Adaptation strategy': 'Estratégia de adaptação',
  'Learning rate η': 'Taxa de aprendizado η',
  'Training epochs': 'Épocas de treino',
  'Inspect training progress': 'Avançar passo a passo',
  'Decision surface': 'Superfície de decisão',
  epoch: 'época',
  'train loss': 'perda de treino',
  'validation accuracy': 'acurácia de validação',
  'training accuracy': 'acurácia de treino',
  'log loss': 'log da perda',
  inertia: 'inércia',
  Epoch: 'Época',
  Trees: 'Árvores',
  Depth: 'Profundidade',
  'Training points': 'Pontos de treino',
  Iteration: 'Iteração',
  'Nine classifiers, one plane': 'Nove classificadores, um plano',
  'Pick a family, then watch it train': 'Escolha uma família e acompanhe o treino',
  'The nine, side by side': 'Os nove, lado a lado',
  'Pick one, then watch it train below': 'Escolha um e veja o treino abaixo',
  'Replay the training': 'Rodar o treino de novo',
  Pause: 'Pausar',
  Trained: 'Treinado',
  'Step through the training': 'Avançar passo a passo',
  'Class 1': 'Classe 1',
  'Class 0': 'Classe 0',
  Validation: 'Validação',
  Linear: 'Linear',
  Circle: 'Círculo',
  'Frozen': 'Congelado',
  'Full': 'Completo',
  epochs: 'épocas',
  'Next step': 'Passo',
  'k-NN': 'k vizinhos',
  'k-means': 'k-médias',
  'Model': 'Modelo',
  'Training / role': 'Treino / papel',
  'Useful distinction': 'Distinção útil',
  'Masked protein language modeling': 'Modelagem mascarada de linguagem de proteínas',
  'Contextual residue embeddings': 'Embeddings contextuais de resíduo',
  'Structure prediction using ESM-2': 'Predição de estrutura usando o ESM-2',
  'Includes a folding architecture': 'Inclui uma arquitetura de enovelamento',
  'BERT-style masked protein modeling': 'Modelagem mascarada de proteína no estilo BERT',
  'Protein encoder within ProtTrans': 'Codificador de proteínas dentro do ProtTrans',
  'T5-based protein pretraining': 'Pré-treino de proteínas baseado em T5',
  'Its encoder is commonly used for embeddings': 'O codificador dele é o usado para embeddings',
  'A causal language model predicts the next token using earlier context. Our count model uses the previous word only.': 'Um modelo de linguagem causal prevê o próximo token usando o contexto anterior. Nosso modelo de contagem usa apenas a palavra anterior.',
  'A hidden target. In BERT, the loss is computed at selected positions.': 'Um alvo escondido. No BERT, a perda é calculada nas posições escolhidas.',
  'A masked-token head predicts vocabulary labels at selected positions. A sequence-classification head may use a pooled representation. The choice depends on the learning objective.': 'Uma cabeça de token mascarado prevê rótulos do vocabulário nas posições escolhidas. Uma cabeça de classificação de sequência pode usar uma representação agregada. A escolha depende do objetivo de aprendizado.',
  'Another skip connection and normalization complete the block. Repeating the block builds progressively contextual representations.': 'Outra conexão de atalho e a normalização fecham o bloco. Repetir o bloco constrói representações cada vez mais contextuais.',
  'BERT’s masked objective uses context on both sides of selected tokens. Our small count model demonstrates the idea.': 'O objetivo mascarado do BERT usa contexto dos dois lados dos tokens escolhidos. Nosso modelo pequeno de contagem demonstra a ideia.',
  'Each head uses different projections. Head outputs are concatenated and projected back to the model dimension. The heatmap above shows one head at a time.': 'Cada cabeça usa projeções diferentes. As saídas são concatenadas e projetadas de volta à dimensão do modelo. O mapa de calor acima mostra uma cabeça por vez.',
  'Each hidden unit learns a different weighted combination, then applies tanh. Backpropagation multiplies the upstream derivative by 1 − tanh(z)².': 'Cada unidade oculta aprende uma combinação ponderada diferente e aplica tanh. A retropropagação multiplica a derivada que vem de cima por 1 − tanh(z)².',
  'Future positions are masked before softmax. Their attention weights are exactly zero.': 'As posições futuras são mascaradas antes do softmax. O peso de atenção delas é exatamente zero.',
  'Learns contextual residue representations using masked protein sequence modeling. Its embeddings can feed task-specific heads. The largest ESM-2 model in the 2023 work has 15 billion parameters.': 'Aprende representações contextuais de resíduo com modelagem mascarada de sequências de proteína. Os embeddings alimentam cabeças específicas de tarefa. O maior ESM-2 do trabalho de 2023 tem 15 bilhões de parâmetros.',
  'Masking hides a residue identity so a model must use sequence context to predict the target.': 'O mascaramento esconde a identidade de um resíduo, então o modelo precisa usar o contexto da sequência para prever o alvo.',
  'Part of ProtTrans, ProtT5 adapts a T5-based pretraining approach to proteins. The encoder is commonly used to extract per-residue and per-protein embeddings for downstream tasks.': 'Parte do ProtTrans, o ProtT5 adapta o pré-treino baseado em T5 para proteínas. O codificador é usado para extrair embeddings por resíduo e por proteína para tarefas adiante.',
  'Part of the ProtTrans project, ProtBERT adapts BERT-style masked language modeling to protein sequences. It connects the language gallery’s encoder design directly to biological sequence representation learning.': 'Parte do projeto ProtTrans, o ProtBERT adapta a modelagem mascarada no estilo BERT para sequências de proteína. Ele liga o desenho de codificador da galeria de linguagem ao aprendizado de representações biológicas.',
  'The output neuron maps a weighted sum of the six hidden values to p(class 1). With sigmoid and binary cross-entropy, the derivative with respect to its pre-activation is p − y.': 'O neurônio de saída leva a soma ponderada dos seis valores ocultos a p(classe 1). Com sigmoide e entropia cruzada binária, a derivada em relação ao valor antes da ativação é p − y.',
  'The residual path carries the previous representation forward. Layer normalization controls activation scale. This diagram uses the original post-normalization ordering.': 'O caminho residual leva a representação anterior adiante. A normalização de camada controla a escala das ativações. Este diagrama usa a ordem original, com normalização depois.',
  'The same feed-forward network transforms each position separately. It usually expands and then contracts the hidden dimension. Modern variants may use GELU or gated activations.': 'A mesma rede feed-forward transforma cada posição em separado. Ela costuma expandir e depois contrair a dimensão oculta. Variantes modernas usam GELU ou ativações com portas.',
  'This weight controls how much this key’s value vector contributes to the query’s output.': 'Este peso controla quanto o vetor de valor desta chave contribui para a saída da consulta.',
  'Token identities become vectors. Position information makes order available to the model. Original Transformers use sinusoidal encodings; other families use different mechanisms.': 'As identidades dos tokens viram vetores. A informação de posição entrega a ordem ao modelo. Os Transformers originais usam codificação senoidal; outras famílias usam mecanismos diferentes.',
  'Uses an ESM-2 language model together with a folding architecture to predict atomic coordinates. A language-model embedding is an intermediate representation, not a finished 3D structure.': 'Usa um modelo de linguagem ESM-2 junto de uma arquitetura de enovelamento para prever coordenadas atômicas. Um embedding de modelo de linguagem é uma representação intermediária, não uma estrutura 3D pronta.',
  'Artificial intelligence': 'Inteligência artificial',
  'Machine learning': 'Aprendizado de máquina',
  'Deep learning': 'Aprendizado profundo',
  'Transformers': 'Transformers',
  'Language models': 'Modelos de linguagem',
  'Protein language models': 'Modelos de linguagem de proteínas',
  'The broad ambition: systems that perform tasks associated with intelligence. Includes learned models and rule-based systems.': 'A ambição ampla: sistemas que executam tarefas associadas à inteligência. Inclui modelos aprendidos e sistemas de regras.',
  'Systems learn patterns from examples. The learned rule generalizes to observations it did not see during training.': 'Sistemas aprendem padrões a partir de exemplos. A regra aprendida generaliza para observações que não viu no treino.',
  'Neural networks learn a succession of representations. Layers and nonlinear activations turn simple operations into expressive functions.': 'Redes neurais aprendem uma sequência de representações. Camadas e ativações não lineares transformam operações simples em funções expressivas.',
  'An architecture that mixes information between tokens with attention, then transforms it with feed-forward layers.': 'Uma arquitetura que mistura informação entre tokens com atenção e depois a transforma com camadas feed-forward.',
  'Models assign probabilities to token sequences. BERT learns masked representations; causal models learn next-token prediction.': 'Os modelos atribuem probabilidades a sequências de tokens. O BERT aprende representações mascaradas; modelos causais aprendem a prever o próximo token.',
  'Sequence models trained on amino acids. Their contextual embeddings can support predictions about protein structure and function.': 'Modelos de sequência treinados em aminoácidos. Os embeddings contextuais deles sustentam predições sobre estrutura e função de proteínas.',
  'Planning · search · expert systems': 'Planejamento · busca · sistemas especialistas',
  'Regression · trees · support vector machines': 'Regressão · árvores · máquinas de vetores de suporte',
  'MLPs · CNNs · recurrent networks': 'MLPs · CNNs · redes recorrentes',
  'Attention + feed-forward + residuals': 'Atenção + feed-forward + residuais',
  'BERT · GPT-style decoder models': 'BERT · modelos decodificadores no estilo GPT',
  'ESM-2 · ProtBERT · ProtT5': 'ESM-2 · ProtBERT · ProtT5',
  'A map of machine intelligence': 'Um mapa da inteligência de máquina',
  'Select an idea to look inside': 'Escolha uma ideia para olhar por dentro',
  'Training': 'Treino',
  probability: 'de probabilidade',
  Class: 'Classe',
  'Input x₁ is a numerical feature. Increasing it raises z when its weight is positive, and lowers z when its weight is negative.': 'A entrada x₁ é um atributo numérico. Aumentá-la eleva z quando o peso é positivo, e reduz z quando o peso é negativo.',
  'Input x₂ enters separately. Its contribution is its value multiplied by w₂, not its value alone.': 'A entrada x₂ entra separada. A contribuição dela é o valor multiplicado por w₂, não o valor sozinho.',
  'ReLU clips negative values to zero. Positive values pass through, so its output is not a probability.': 'A ReLU corta valores negativos em zero. Os positivos passam, então a saída não é uma probabilidade.',
  'Sigmoid smoothly maps z to a number between 0 and 1. In binary classification this can represent a modeled class probability.': 'A sigmoide leva z suavemente a um número entre 0 e 1. Em classificação binária, isso pode representar a probabilidade modelada da classe.',
  'Synthetic source and target tasks. This demonstrates transfer learning, not real pLM fine-tuning.': 'Tarefas de origem e destino sintéticas. Isto demonstra transferência de aprendizado, não ajuste fino de um pLM real.',
  'Task X: classify opposite quadrants (XOR). No protein solubility labels are used.': 'Tarefa X: classificar quadrantes opostos (XOR). Nenhum rótulo de solubilidade de proteína é usado.',
  '100 training points; 60 separate validation points. Every run uses the same split and initialization.': '100 pontos de treino; 60 pontos de validação separados. Toda execução usa a mesma divisão e a mesma inicialização.',
  'The weighted sum combines each input contribution and the bias before any activation is applied.': 'A soma ponderada junta a contribuição de cada entrada e o viés antes de qualquer ativação.',
  'Select a node to understand its role. No training happens when you move these sliders.': 'Escolha um nó para entender o papel dele. Mexer nestes controles não treina nada.',
  'The initial surface is untrained. Run the experiment to compute the full trajectory.': 'A superfície inicial não foi treinada. Rode o experimento para calcular a trajetória inteira.',
  'Reset': 'Restaurar',
  'Only the points inside the margin push the boundary. The rest could be deleted without changing it.': 'Só os pontos dentro da margem empurram a fronteira. O resto poderia ser apagado sem mudá-la.',
  'A curved boundary without curved features: the kernel measures distance, and distance is not linear.': 'Uma fronteira curva sem atributos curvos: o kernel mede distância, e distância não é linear.',
  'Every boundary is an axis-aligned cut, which is why the regions come out as rectangles.': 'Toda fronteira é um corte alinhado a um eixo, e é por isso que as regiões saem retangulares.',
  'Averaging many overfitted trees is not the same as one shallow tree. The variance cancels; the signal does not.': 'Tirar a média de muitas árvores sobreajustadas não é o mesmo que uma árvore rasa. A variância se cancela; o sinal não.',
  'Depth two, not one: a single stump adds one feature to another and can never represent XOR. Watch the validation curve after it peaks, too.': 'Profundidade dois, não um: um toco sozinho soma um atributo ao outro e nunca representa o XOR. Observe também a curva de validação depois do pico.',
  'It assumes the two features are independent given the class. They are not, and it often works anyway.': 'Ele supõe que os dois atributos são independentes dada a classe. Não são, e mesmo assim costuma funcionar.',
  'The loss here is inertia, not error: it never saw a label. Accuracy is measured afterwards, by asking what each group turned out to be.': 'A perda aqui é inércia, não erro: ele nunca viu um rótulo. A acurácia é medida depois, perguntando no que cada grupo deu.',
  'Three numbers decide everything: two weights and a bias. The boundary can only ever be a straight line.': 'Três números decidem tudo: dois pesos e um viés. A fronteira só pode ser uma reta.',
  'Activation': 'Ativação',
  'Attention calculation failed.': 'O cálculo da atenção falhou.',
  'BERT meets next-token prediction': 'O BERT encontra a predição do próximo token',
  'BERT’s encoder can attend in both directions.': 'O codificador do BERT pode atender nos dois sentidos.',
  'Backward: ∂L/∂p → ∂L/∂h → ∂L/∂W': 'Reverso: ∂L/∂p → ∂L/∂h → ∂L/∂W',
  'Calculate probabilities': 'Calcular probabilidades',
  'Calculating…': 'Calculando…',
  'Causal masking prevents looking at future tokens.': 'A máscara causal impede olhar tokens futuros.',
  'Could not calculate probabilities.': 'Não foi possível calcular as probabilidades.',
  'Differentiable neuron demonstration': 'Demonstração de neurônio diferenciável',
  'ESM-2: a masked protein encoder': 'ESM-2: um codificador de proteínas mascarado',
  'ESMFold: from representations to structure': 'ESMFold: das representações à estrutura',
  'Earlier context': 'Contexto anterior',
  'Enter 4–40 standard amino-acid letters. Spaces are ignored.': 'Digite de 4 a 40 letras padrão de aminoácido. Espaços são ignorados.',
  'Exact math · fixed, untrained toy projections': 'Conta exata · projeções fixas, de brinquedo, sem treino',
  'Experiment failed.': 'O experimento falhou.',
  'Explore your own short sequence': 'Explore uma sequência curta sua',
  'Feature x₁': 'Atributo x₁',
  'Feature x₂': 'Atributo x₂',
  'Fill in the missing idea.': 'Complete a ideia que falta.',
  'Forward pass · weights edited manually': 'Passagem direta · pesos editados à mão',
  'Forward: x → h → p → loss': 'Direto: x → h → p → perda',
  'Hidden representations': 'Representações ocultas',
  'Historical perceptron activation': 'Ativação do perceptron histórico',
  'Input features': 'Atributos de entrada',
  'Input sequence': 'Sequência de entrada',
  'Inspect a point. Color = predicted probability; shape = observed class.': 'Inspecione um ponto. Cor = probabilidade prevista; forma = classe observada.',
  'Inspect the layers and the backward pass': 'Inspecionar as camadas e a passagem reversa',
  'Keep the encoder fixed; train only a new linear head.': 'Mantenha o codificador fixo; treine só uma cabeça linear nova.',
  'Keys / columns →': 'Chaves / colunas →',
  'Left + right context': 'Contexto à esquerda e à direita',
  'Live calculation': 'Cálculo ao vivo',
  'Load sequence ': 'Carregar sequência ',
  'Logits / scores': 'Logits / pontuações',
  'LoRA: freeze the base encoder; train a rank-1 weight change and the task head.': 'LoRA: congele o codificador base; treine uma mudança de posto 1 e a cabeça da tarefa.',
  'Make a connection.': 'Faça a ligação.',
  'Mask this residue': 'Mascarar este resíduo',
  'Masked language modeling → contextual embeddings': 'Modelagem de linguagem mascarada → embeddings contextuais',
  'Meet the models': 'Conheça os modelos',
  'Multi-head self-attention': 'Autoatenção de múltiplas cabeças',
  'No matching context; using smoothed unigram counts.': 'Nenhum contexto correspondente; usando contagens de unigrama suavizadas.',
  'One sequence vector': 'Um vetor de sequência',
  'One vector per residue': 'Um vetor por resíduo',
  'Pause training playback': 'Pausar a reprodução do treino',
  'Play training playback': 'Reproduzir o treino',
  'Playback of computed epochs': 'Reprodução das épocas calculadas',
  'Pooled embedding': 'Embedding agregado',
  'Position-wise feed-forward': 'Feed-forward por posição',
  'Pretrained pLM': 'pLM pré-treinado',
  'Primary sequence': 'Sequência primária',
  'ProtBERT: BERT, with an amino-acid vocabulary': 'ProtBERT: o BERT, com vocabulário de aminoácidos',
  'ProtT5: transferable protein representations': 'ProtT5: representações de proteína transferíveis',
  'Protein encoder': 'Codificador de proteínas',
  'Protein sequence': 'Sequência de proteína',
  'Query → key → value': 'Consulta → chave → valor',
  'REPEAT × N TRANSFORMER BLOCKS': 'Repetir × N blocos Transformer',
  'ReLU output': 'Saída da ReLU',
  'Read one row: how a query distributes attention across all keys.': 'Leia uma linha: como uma consulta distribui atenção por todas as chaves.',
  'Recomputing attention…': 'Recalculando a atenção…',
  'Related ideas. Different roles.': 'Ideias próximas. Papéis diferentes.',
  'Residual + normalization': 'Residual + normalização',
  'Residue embeddings': 'Embeddings de resíduo',
  'Residue identities · real descriptors': 'Identidade dos resíduos · descritores reais',
  'Residue tokens': 'Tokens de resíduo',
  'Reveal residue': 'Revelar resíduo',
  'Run the experiment to reveal the distribution.': 'Rode o experimento para revelar a distribuição.',
  'Schematic colors only; no learned embedding is computed here.': 'Cores apenas esquemáticas; nenhum embedding aprendido é calculado aqui.',
  'See the training corpus and what BERT actually computes': 'Ver o corpus de treino e o que o BERT calcula de fato',
  'Self-supervision: the sequence provides the target': 'Autossupervisão: a sequência fornece o alvo',
  'Sentence with one [MASK]': 'Frase com um [MASK]',
  'Source pretraining → new head → task X': 'Pré-treino de origem → cabeça nova → tarefa X',
  'Start a sentence': 'Comece uma frase',
  'Task or vocabulary head': 'Cabeça de tarefa ou de vocabulário',
  'Task or vocabulary head ': 'Cabeça de tarefa ou de vocabulário ',
  'Task-specific head': 'Cabeça específica da tarefa',
  'The input layer holds the two features. It has no trainable parameters by itself.': 'A camada de entrada guarda os dois atributos. Sozinha, ela não tem parâmetros treináveis.',
  'The protein alphabet': 'O alfabeto das proteínas',
  'The threshold outputs class 1 when z ≥ 0, otherwise class 0.': 'O limiar devolve classe 1 quando z ≥ 0, e classe 0 caso contrário.',
  'The whole architecture': 'A arquitetura inteira',
  'Token + position information': 'Token + informação de posição',
  'Token + position information ': 'Token + informação de posição ',
  'Token IDs': 'IDs de token',
  'Top 6 candidates; probabilities sum to 1 across the full vocabulary.': 'Os 6 melhores candidatos; as probabilidades somam 1 no vocabulário inteiro.',
  'Two ways to learn from a sequence': 'Dois jeitos de aprender com uma sequência',
  'Update the encoder and the new task head together.': 'Atualize o codificador e a cabeça nova juntos.',
  'Weighted sum': 'Soma ponderada',
  'What comes next?': 'O que vem depois?',
  'Who attends to whom?': 'Quem atende a quem?',
  'Word tokens · tiny corpus': 'Tokens de palavra · corpus minúsculo',
  'Asparagine': 'Asparagina',
  'Isoleucine': 'Isoleucina',
  'Methionine': 'Metionina',
  'Phenylalanine': 'Fenilalanina',
  'Tryptophan': 'Triptofano',
  'Alanine': 'Alanina',
  'Cysteine': 'Cisteína',
  'Aspartate': 'Aspartato',
  'Glutamate': 'Glutamato',
  'Glutamine': 'Glutamina',
  'Glycine': 'Glicina',
  'Histidine': 'Histidina',
  'Leucine': 'Leucina',
  'Lysine': 'Lisina',
  'Proline': 'Prolina',
  'Serine': 'Serina',
  'Threonine': 'Treonina',
  'Tyrosine': 'Tirosina',
  'Valine': 'Valina',
  'Arginine': 'Arginina',
  'Decision tree': 'Árvore de decisão',
  'Random forest': 'Floresta aleatória',
  'Gradient boosting': 'Gradient boosting',
  'Naive Bayes': 'Naive Bayes',
  'Logistic': 'Logística',
  'SVM, linear': 'SVM linear',
  'SVM, RBF': 'SVM com RBF',
  'Computed in your browser': 'Calculado no seu navegador',
  'A small model. Real updates.': 'Um modelo pequeno. Atualizações de verdade.',
  'Class 1 / train loss': 'Classe 1 / perda de treino',
  'Validation loss': 'Perda de validação',
  'One straight line, three parameters. The baseline every other model has to beat.': 'Uma reta só, três parâmetros. A linha de base que todo modelo tem de superar.',
  'Also a straight line, placed to leave the widest possible gap between the classes.': 'Também uma reta, colocada para deixar a maior folga possível entre as classes.',
  'The same margin idea, measured through a kernel, so the boundary can bend.': 'A mesma ideia de margem, medida por um kernel, então a fronteira pode curvar.',
  'No training at all. The answer is a vote among the nearest stored points.': 'Nenhum treino. A resposta é um voto entre os pontos guardados mais próximos.',
  'A sequence of yes-or-no cuts, each one on a single feature.': 'Uma sequência de cortes de sim ou não, cada um sobre um atributo.',
  'Many overfitted trees, each on a different resample, averaged.': 'Muitas árvores sobreajustadas, cada uma numa reamostragem, tiradas na média.',
  'Small trees added in sequence, each fixing what the previous ones got wrong.': 'Árvores pequenas somadas em sequência, cada uma corrigindo o erro das anteriores.',
  'A closed-form fit: mean and variance per class per feature, then Bayes rule.': 'Um ajuste fechado: média e variância por classe e por atributo, e a regra de Bayes.',
  'Unsupervised. It groups the plane without ever seeing a label.': 'Não supervisionado. Ele agrupa o plano sem nunca ver um rótulo.',
  'Learning rate': 'Taxa de aprendizado',
  'Margin softness C': 'Folga da margem C',
  'Kernel width γ': 'Largura do kernel γ',
  'Largest k swept': 'Maior k varrido',
  'Maximum depth': 'Profundidade máxima',
  'Number of trees': 'Número de árvores',
  'Boosting rounds': 'Rodadas de boosting',
  'Fixed: it has no knob': 'Fixo: não tem botão',
  'Number of clusters k': 'Número de grupos k',
  'k': 'k',
  'Adjust weights. Inspect the signal.': 'Ajuste os pesos. Observe o sinal.',
  'Change context, then compare probabilities': 'Mude o contexto e compare as probabilidades',
  'Hover a cell to follow the calculation': 'Passe por uma célula para seguir o cálculo',
  'Select a layer to see what it does': 'Escolha uma camada para ver o que ela faz',
  'Select a residue, then mask it': 'Escolha um resíduo e mascare-o',
  'Activation function': 'Função de ativação',
  'Attention head': 'Cabeça de atenção',
  'Attention mask': 'Máscara de atenção',
  'Attention matrix. Rows are queries and columns are keys.': 'Matriz de atenção. As linhas são consultas e as colunas são chaves.',
  'Bias b': 'Viés b',
  'Input x₁': 'Entrada x₁',
  'Input x₂': 'Entrada x₂',
  'Language modeling objective': 'Objetivo de modelagem de linguagem',
  'Network layer': 'Camada da rede',
  'Predicted class probabilities across a two-feature plane; circles are class 0 and diamonds class 1 training examples': 'Probabilidades de classe previstas num plano de dois atributos; círculos são exemplos de treino da classe 0 e losangos da classe 1',
  'Protein model': 'Modelo de proteína',
  'Real protein fine-tuning workflow': 'Fluxo real de ajuste fino de proteína',
  'Schematic embedding matrix with one row per residue, followed by mean pooling into one sequence vector': 'Matriz de embedding esquemática com uma linha por resíduo, seguida de agregação por média num vetor de sequência',
  'Temperature': 'Temperatura',
  'Token domain': 'Domínio do token',
  'Two input features connected to six hidden neurons and one output': 'Dois atributos de entrada ligados a seis neurônios ocultos e uma saída',
  'Weight w₁': 'Peso w₁',
  'Weight w₂': 'Peso w₂',
  'A sequence becomes a representation': 'Uma sequência vira uma representação',
  'Build a Transformer block': 'Montar um bloco Transformer',
  'Inside self-attention': 'Dentro da autoatenção',
  'The neuron workbench': 'A bancada do neurônio',
  'Amino acids': 'Aminoácidos',
  'Bidirectional': 'Bidirecional',
  'Causal': 'Causal',
  'Head 1': 'Cabeça 1',
  'Head 2': 'Cabeça 2',
  'Head 3': 'Cabeça 3',
  'Conformationally restricted': 'Restrito conformacionalmente',
  'Held-out evaluation': 'Avaliação em dados separados',
  'Hydrophobic / aromatic': 'Hidrofóbico / aromático',
  'Hydrophobic / sulfur-containing': 'Hidrofóbico / com enxofre',
  'Hydrophobic': 'Hidrofóbico',
  'Ionizable / aromatic': 'Ionizável / aromático',
  'Negatively charged': 'Carga negativa',
  'Positively charged': 'Carga positiva',
  'Next token': 'Próximo token',
  'Output probability': 'Probabilidade de saída',
  'Polar / aromatic': 'Polar / aromático',
  'Polar / sulfur-containing': 'Polar / com enxofre',
  'Polar': 'Polar',
  'Small / flexible': 'Pequeno / flexível',
  'Words': 'Palavras',
  'Sigmoid': 'Sigmoide',
  'Step': 'Degrau',
  'ReLU': 'ReLU',
  'XOR': 'XOR',
  'BERT-style mask': 'Máscara estilo BERT',
  'Masked': 'Mascarado',
  'LoRA': 'LoRA',
  '2 inputs → 6 tanh neurons → sigmoid': '2 entradas → 6 neurônios tanh → sigmoide',
  '2 inputs → sigmoid → class': '2 entradas → sigmoide → classe',
  '3 independent heads': '3 cabeças independentes',
  'A real BERT pass': 'Uma passagem real do BERT',
  'Applications': 'Aplicações',
  'Architecture': 'Arquitetura',
  'BERT is an encoder reference, not an autoregressive chat model. ProtBERT applies a related masked-encoder idea to protein sequences.': 'O BERT é uma referência de codificador, não um modelo de conversa autorregressivo. O ProtBERT aplica a ideia de codificador mascarado a sequências de proteína.',
  'BERT · decoder LLMs': 'BERT · LLMs decodificadoras',
  'CNNs · RNNs · and more': 'CNNs · RNNs · e mais',
  'Chemical grouping is simplified. Charge depends on pH. No structure or function prediction is performed.': 'O agrupamento químico é simplificado. A carga depende do pH. Nenhuma predição de estrutura ou função é feita.',
  'Count-based demonstration trained from 12 displayed sentences. These are not BERT outputs.': 'Demonstração por contagem treinada com as 12 frases exibidas. Estas não são saídas do BERT.',
  'Explore the exhibit': 'Ver o experimento',
  'Explore with mouse, touch or keyboard': 'Explore com mouse, toque ou teclado',
  'Fields': 'Campos',
  'Hover or select to explore': 'Passe o cursor ou selecione para explorar',
  'Interactive exhibit': 'Experimento interativo',
  'Load sequence': 'Carregar sequência',
  'Nested fields, connected ideas. Architecture and training objective are different concepts.': 'Campos aninhados, ideias conectadas. Arquitetura e objetivo de treino são conceitos diferentes.',
  'On display': 'Em exibição',
  'One family of architectures. More than one language.': 'Uma família de arquiteturas. Mais de uma linguagem.',
  'Output': 'Saída',
  'Position': 'Posição',
  'Query': 'Consulta',
  'Select to discover': 'Escolha para descobrir',
  'Text language models': 'Modelos de linguagem de texto',
  'The architecture': 'A arquitetura',
  'The corpus and the predicted candidates are in English: they are the input data of the experiment.': 'O corpus e os candidatos previstos estão em inglês: são o dado de entrada do experimento.',
  'The count demo learns frequencies from these sentences. Its displayed scores are log(count + 0.1) / temperature before softmax.': 'A demonstração por contagem aprende frequências destas frases. As pontuações exibidas são log(contagem + 0,1) / temperatura antes do softmax.',
  'The optimizer subtracts learning rate × gradient from each trainable parameter.': 'O otimizador subtrai taxa de aprendizado × gradiente de cada parâmetro treinável.',
  'Training and validation accuracy across the training axis': 'Acurácia de treino e de validação ao longo do eixo de treino',
  'WordPiece tokens → token, position and segment embeddings → stacked bidirectional Transformer encoder blocks → masked-token prediction head → vocabulary softmax. Cross-entropy at selected targets supplies gradients during training. Original BERT also trained a next-sentence objective.': 'Tokens WordPiece → embeddings de token, posição e segmento → blocos codificadores Transformer bidirecionais empilhados → cabeça de predição do token mascarado → softmax sobre o vocabulário. A entropia cruzada nos alvos selecionados fornece os gradientes durante o treino. O BERT original também treinava um objetivo de próxima frase.',
  'attention': 'atenção',
  'attention weight': 'peso de atenção',
  'base parameters': 'parâmetros base',
  'bias': 'viés',
  'hydrophobic': 'hidrofóbico',
  'key': 'chave',
  'matching context occurrences.': 'ocorrências de contexto correspondentes.',
  'parameters': 'parâmetros',
  'percent': 'por cento',
  'predicted p(class 1)': 'p(classe 1) prevista',
  'residues': 'resíduos',
  'row': 'linha',
  'to': 'a',
  'total parameters': 'parâmetros no total',
  'trainable': 'treináveis',
  'trainable parameters': 'parâmetros treináveis',
  'trees · regression · kernels': 'árvores · regressão · kernels',
  'Fourteen models, read one by one': 'Catorze modelos, lidos um a um',
  'AlphaFold, ESM, ProteinMPNN, RFdiffusion and their successors': 'AlphaFold, ESM, ProteinMPNN, RFdiffusion e seus sucessores',
  'Side by side': 'Lado a lado',
  'ESM-2 against ESM3 and ESM C, AlphaFold 2 against 3, ESMFold against ESMFold2': 'ESM-2 contra ESM3 e ESM C, AlphaFold 2 contra 3, ESMFold contra ESMFold2',
  'Start with AlphaFold 2': 'Comece pelo AlphaFold 2',
  'Seven components, from the alignment to the confidence heads': 'Sete componentes, do alinhamento às cabeças de confiança',
  'Exhibit': 'Experimento',
  'Build a decision, one weight at a time.': 'Construa uma decisão, um peso por vez.',
  'Watch tokens exchange information.': 'Veja tokens trocarem informação.',
  'Discover what proteins can teach a model.': 'Descubra o que as proteínas ensinam a um modelo.',
  'BERT: bidirectional encoder. GPT-style model: causal decoder. A full encoder-decoder Transformer also uses cross-attention in its decoder.': 'BERT: codificador bidirecional. Modelo estilo GPT: decodificador causal. Um Transformer codificador-decodificador completo também usa atenção cruzada no decodificador.',
};
