// Dicionario em portugues. Os identificadores sao os mesmos de glossary.ts,
// entao um termo sem traducao aparece em ingles em vez de sumir da lista.
// Os apelidos guardam tambem a forma em ingles: e assim que a palavra
// costuma aparecer em artigo e em codigo, e a busca precisa achar as duas.

export const categoriesPt: Record<string, string> = {
  Foundations: 'Fundamentos',
  'Neural networks': 'Redes neurais',
  Training: 'Treino',
  'Language & attention': 'Linguagem e atenção',
  Proteins: 'Proteínas',
};

export type TermPt = {name: string; aliases: string[]; plain: string; technical: string; example: string};

export const glossaryPt: Record<string, TermPt> = {
  ai: {
    name: 'Inteligência artificial',
    aliases: ['IA', 'AI', 'artificial intelligence'],
    plain: 'O campo que faz computadores executarem tarefas associadas à inteligência.',
    technical: 'Inclui sistemas baseados em aprendizado e abordagens simbólicas como regras, busca e planejamento.',
    example: 'Um programa de xadrez baseado em busca pode ser IA sem ser uma rede neural.',
  },
  ml: {
    name: 'Aprendizado de máquina',
    aliases: ['ML', 'machine learning', 'aprendizado de maquina'],
    plain: 'Ensinar um computador a partir de exemplos, em vez de escrever cada regra de decisão.',
    technical: 'Algoritmos ajustam parâmetros ou estruturas aos dados para melhorar um objetivo.',
    example: 'Treinar um classificador com observações rotuladas.',
  },
  dl: {
    name: 'Aprendizado profundo',
    aliases: ['DL', 'deep learning'],
    plain: 'Aprendizado de máquina que usa redes neurais com várias camadas de processamento.',
    technical: 'Camadas não lineares compõem representações aprendidas; profundidade não é o mesmo que muitos parâmetros.',
    example: 'Um Transformer empilha blocos de atenção e feed-forward.',
  },
  model: {
    name: 'Modelo',
    aliases: ['model'],
    plain: 'Um sistema matemático que transforma entradas em saídas.',
    technical: 'A arquitetura define o cálculo; os parâmetros aprendidos determinam o comportamento específico.',
    example: 'Um modelo de regressão logística leva dois atributos a uma probabilidade de classe.',
  },
  feature: {
    name: 'Atributo',
    aliases: ['atributos', 'feature', 'features', 'variável'],
    plain: 'Uma informação mensurável entregue ao modelo.',
    technical: 'Uma variável de entrada pode ser desenhada à mão ou aprendida por uma representação anterior.',
    example: 'O comprimento da proteína ou a fração de aminoácidos hidrofóbicos.',
  },
  label: {
    name: 'Rótulo',
    aliases: ['rótulos', 'rotulo', 'label', 'labels'],
    plain: 'A resposta alvo ligada a um exemplo de treino.',
    technical: 'Um alvo supervisionado pode ser uma classe, um número ou uma saída estruturada.',
    example: 'Uma anotação medida em bancada de solúvel ou insolúvel.',
  },
  dataset: {
    name: 'Conjunto de dados',
    aliases: ['dataset', 'base de dados'],
    plain: 'Uma coleção de exemplos usada para treinar ou avaliar um modelo.',
    technical: 'As divisões têm papéis distintos: treino ajusta parâmetros; validação guia escolhas; teste estima o desempenho final.',
    example: 'Uma tabela de sequências de proteína e propriedades medidas.',
  },
  node: {
    name: 'Nó',
    aliases: ['nós', 'neurônio', 'neuronio', 'node', 'nodes', 'neuron'],
    plain: 'Uma unidade pequena de processamento no diagrama de uma rede neural.',
    technical:
      'Um neurônio costuma calcular uma soma ponderada mais um viés, seguida de uma ativação. Nó de grafo tem sentido mais amplo fora de redes neurais.',
    example: 'Cada círculo do experimento do neurônio é uma unidade de cálculo, não uma célula cerebral.',
  },
  perceptron: {
    name: 'Perceptron',
    aliases: ['perceptrons'],
    plain: 'Um neurônio artificial antigo que toma uma decisão de sim ou não.',
    technical: 'O perceptron histórico usa um limiar duro sobre w·x + b e uma regra de atualização guiada por erro.',
    example: 'Dois atributos separados em classes por uma fronteira reta.',
  },
  weight: {
    name: 'Peso',
    aliases: ['pesos', 'weight', 'weights'],
    plain: 'Um número que controla a influência de uma entrada no cálculo.',
    technical: 'Um coeficiente treinável numa transformação afim; pode ser positivo ou negativo.',
    example: 'Com peso −0,5, uma entrada de 0,4 contribui com −0,2 para a soma.',
  },
  bias: {
    name: 'Viés',
    aliases: ['vies', 'bias'],
    plain: 'Um deslocamento ajustável que move a resposta de um neurônio.',
    technical: 'O termo aditivo b em z = w·x + b. Este sentido não é o de viés de conjunto de dados nem de viés social.',
    example: 'Mesmo com todas as entradas em zero, um viés de 0,3 deixa z = 0,3.',
  },
  parameter: {
    name: 'Parâmetro',
    aliases: ['parâmetros', 'parametro', 'parameter', 'parameters'],
    plain: 'Um número guardado que ajuda a definir o comportamento do modelo.',
    technical: 'Pesos e vieses são parâmetros. Hiperparâmetros, como a taxa de aprendizado, governam o processo de treino.',
    example: 'Um neurônio com dois pesos e um viés tem três parâmetros.',
  },
  activation: {
    name: 'Ativação',
    aliases: ['função de ativação', 'ativacao', 'activation', 'activations'],
    plain: 'A regra que transforma a soma ponderada de um neurônio na saída dele.',
    technical: 'Uma ativação não linear permite que camadas compostas representem funções não lineares.',
    example: 'Sigmoide, tanh e ReLU são ativações comuns.',
  },
  sigmoid: {
    name: 'Sigmoide',
    aliases: ['sigmoid'],
    plain: 'Uma função suave em forma de S que espreme um número entre 0 e 1.',
    technical: 'σ(z) = 1 / (1 + exp(−z)); costuma vir acompanhada da entropia cruzada binária.',
    example: 'Em z = 0, a sigmoide devolve 0,5.',
  },
  relu: {
    name: 'ReLU',
    aliases: ['unidade linear retificada'],
    plain: 'Uma ativação que mantém valores positivos e zera os negativos.',
    technical: 'Unidade linear retificada: ReLU(z) = max(0,z). A saída não tem teto.',
    example: 'ReLU(−2) = 0; ReLU(3) = 3.',
  },
  layer: {
    name: 'Camada',
    aliases: ['camadas', 'camada oculta', 'layer', 'hidden layer'],
    plain: 'Um grupo de cálculos no mesmo estágio de uma rede.',
    technical: 'Uma camada oculta transforma uma representação interna entre a entrada e a saída.',
    example: 'A rede pequena tem seis unidades tanh numa camada oculta.',
  },
  mlp: {
    name: 'Perceptron de múltiplas camadas',
    aliases: ['MLP', 'multilayer perceptron'],
    plain: 'Uma rede direta feita de camadas conectadas de neurônios artificiais.',
    technical: 'Costuma alternar transformações afins com ativações não lineares.',
    example: 'A rede 2 → 6 → 1 consegue aprender uma fronteira não linear.',
  },
  loss: {
    name: 'Perda',
    aliases: ['função de perda', 'loss', 'custo'],
    plain: 'Um número que mede o quanto uma predição erra o alvo.',
    technical: 'A otimização procura parâmetros que reduzam um objetivo calculado na média dos exemplos de treino.',
    example: 'Prever 0,01 para um positivo verdadeiro custa muita entropia cruzada.',
  },
  'cross-entropy': {
    name: 'Entropia cruzada',
    aliases: ['entropia cruzada binária', 'cross-entropy'],
    plain: 'Uma perda que pune atribuir probabilidade baixa à resposta certa.',
    technical: 'Para rótulos binários: −[y log p + (1−y) log(1−p)].',
    example: 'Uma predição errada e confiante custa mais que uma incerta.',
  },
  gradient: {
    name: 'Gradiente',
    aliases: ['gradientes', 'gradient'],
    plain: 'Um conjunto de inclinações que mostra como a perda muda quando os parâmetros mudam.',
    technical: 'O vetor de derivadas parciais ∇θL aponta para a subida mais íngreme local na geometria euclidiana.',
    example: 'A descida de gradiente anda um pouco na direção oposta.',
  },
  backpropagation: {
    name: 'Retropropagação',
    aliases: ['backpropagation', 'passagem reversa', 'retropropagacao'],
    plain: 'Voltar pela rede para descobrir como cada parâmetro afetou a perda.',
    technical: 'A regra da cadeia calcula os gradientes de forma eficiente pelo grafo de computação.',
    example: 'O erro da saída é propagado pela camada oculta até os pesos de entrada.',
  },
  'learning-rate': {
    name: 'Taxa de aprendizado',
    aliases: ['learning rate'],
    plain: 'O tamanho de cada passo de atualização dos parâmetros durante o treino.',
    technical: 'Um hiperparâmetro η em θ ← θ − η∇θL.',
    example: 'Uma taxa muito pequena aprende devagar; uma grande pode passar do ponto.',
  },
  epoch: {
    name: 'Época',
    aliases: ['épocas', 'epoca', 'epoch', 'epochs'],
    plain: 'Uma passagem completa pelo conjunto de treino.',
    technical: 'Uma época pode conter muitos passos do otimizador se os exemplos forem divididos em lotes.',
    example: 'Este laboratório usa lote completo: uma atualização por época.',
  },
  batch: {
    name: 'Lote',
    aliases: ['lotes', 'batch', 'mini-lote'],
    plain: 'Um grupo de exemplos processados juntos num passo de treino.',
    technical: 'Gradientes de minilote estimam o gradiente do conjunto inteiro.',
    example: 'Um lote de 32 proteínas produz uma atualização do otimizador.',
  },
  overfitting: {
    name: 'Sobreajuste',
    aliases: ['overfitting', 'sobre-ajuste'],
    plain: 'Aprender detalhes dos exemplos de treino que não generalizam.',
    technical: 'Erro baixo no treino com desempenho pior fora dele sinaliza sobreajuste ou mudança de distribuição.',
    example: 'Decorar sequências quase idênticas infla a pontuação de uma divisão aleatória.',
  },
  validation: {
    name: 'Validação',
    aliases: ['conjunto de validação', 'validacao', 'validation'],
    plain: 'Exemplos usados para julgar escolhas de treino sem ajustar pesos diretamente neles.',
    technical: 'Escolher configurações repetidamente pela validação a torna parte da seleção do modelo; ainda é preciso um teste intocado.',
    example: 'Escolher a época de parada pela perda de validação.',
  },
  inference: {
    name: 'Inferência',
    aliases: ['inferencia', 'inference'],
    plain: 'Usar um modelo já treinado para produzir uma saída.',
    technical: 'Uma passagem direta comum em inferência não atualiza parâmetros de treino.',
    example: 'Prever um token mascarado é inferência; aprender com o erro dele é treino.',
  },
  pretraining: {
    name: 'Pré-treino',
    aliases: ['pretraining', 'pre-treino', 'pré-treinamento'],
    plain: 'Aprender padrões gerais antes de adaptar a uma tarefa específica.',
    technical: 'Costuma usar objetivos autossupervisionados em grandes conjuntos sem rótulo.',
    example: 'Prever aminoácidos escondidos em muitas sequências de proteína.',
  },
  'fine-tuning': {
    name: 'Ajuste fino',
    aliases: ['fine-tuning', 'fine tuning'],
    plain: 'Continuar o treino para adaptar um modelo existente a uma tarefa ou domínio novo.',
    technical: 'Atualiza parte ou todos os parâmetros do modelo com um objetivo de adaptação.',
    example: 'Adaptar um codificador de proteínas pré-treinado e um classificador a dados de localização rotulados.',
  },
  frozen: {
    name: 'Congelado',
    aliases: ['codificador congelado', 'frozen'],
    plain: 'Mantido fixo enquanto outras partes do modelo aprendem.',
    technical: 'Parâmetros congelados não recebem atualização do otimizador.',
    example: 'Numa sonda linear, o codificador fica fixo e a cabeça da tarefa aprende.',
  },
  head: {
    name: 'Cabeça da tarefa',
    aliases: ['cabeça de classificação', 'task head', 'head'],
    plain: 'O componente final que converte uma representação na saída de que você precisa.',
    technical: 'Um classificador, regressor ou preditor de token acoplado a um codificador. Diferente de cabeça de atenção.',
    example: 'Uma saída sigmoide prevê um rótulo binário de proteína.',
  },
  lora: {
    name: 'LoRA',
    aliases: ['adaptação de baixo posto', 'low-rank adaptation'],
    plain: 'Adaptar um modelo aprendendo matrizes pequenas somadas, mantendo os pesos originais fixos.',
    technical: 'A adaptação de baixo posto representa ΔW = BA, em geral escalada por α/r, em matrizes escolhidas.',
    example: 'Numa matriz de pesos 6×2, os fatores de posto 1 têm 6 + 2 entradas treináveis.',
  },
  rank: {
    name: 'Posto',
    aliases: ['baixo posto', 'rank', 'low-rank'],
    plain: 'O número de direções independentes que uma matriz consegue representar.',
    technical: 'Um produto BA com dimensão interna r tem posto no máximo r.',
    example: 'Uma atualização de posto 1 muda a matriz de pesos numa única direção de produto externo.',
  },
  token: {
    name: 'Token',
    aliases: ['tokens'],
    plain: 'Uma peça discreta de uma sequência que o modelo processa.',
    technical: 'A tokenização leva texto ou sequências a identificadores de vocabulário; tokens não precisam ser palavras inteiras.',
    example: 'Um pedaço de palavra no BERT, ou uma letra de aminoácido em muitos pLMs.',
  },
  embedding: {
    name: 'Embedding',
    aliases: ['embeddings', 'vetor de representação'],
    plain: 'Um vetor de números que representa um token ou uma sequência.',
    technical: 'Coordenadas aprendidas guardam informação estatística útil; as dimensões em geral não têm sentido físico individual.',
    example: 'Um codificador de proteínas produz um vetor contextual para cada resíduo.',
  },
  vector: {
    name: 'Vetor',
    aliases: ['vetores', 'vector'],
    plain: 'Uma lista ordenada de números.',
    technical: 'Representa um ponto, uma direção ou um conjunto de atributos num espaço de coordenadas.',
    example: '[0,2, −0,5, 1,1] é um vetor de três dimensões.',
  },
  matrix: {
    name: 'Matriz',
    aliases: ['matrizes', 'matrix'],
    plain: 'Uma tabela retangular de números usada nos cálculos.',
    technical: 'Pode representar uma transformação linear ou uma coleção de vetores.',
    example: 'Uma matriz de atenção tem uma linha por consulta e uma coluna por chave.',
  },
  logit: {
    name: 'Logit',
    aliases: ['logits'],
    plain: 'Uma pontuação bruta, antes de virar probabilidade.',
    technical: 'O softmax transforma logits de vocabulário em probabilidades normalizadas.',
    example: 'Um logit maior dá ao token mais probabilidade que aos outros.',
  },
  softmax: {
    name: 'Softmax',
    aliases: [],
    plain: 'Transforma uma lista de pontuações em pesos positivos que somam um.',
    technical: 'softmax(z)i = exp(zi) / Σj exp(zj), em geral calculado depois de subtrair a maior pontuação, por estabilidade.',
    example: 'Cada linha de atenção é uma distribuição de probabilidade sobre as chaves permitidas.',
  },
  temperature: {
    name: 'Temperatura',
    aliases: ['temperature'],
    plain: 'Um ajuste que deixa a distribuição de probabilidade mais concentrada ou mais espalhada.',
    technical: 'Os logits são divididos por T antes do softmax. T menor concentra mais a probabilidade.',
    example: 'Aumentar a temperatura espalha a probabilidade do próximo token por mais candidatos.',
  },
  attention: {
    name: 'Atenção',
    aliases: ['autoatenção', 'atencao', 'attention', 'self-attention'],
    plain: 'Um jeito de cada token combinar informação de outros tokens usando pesos de relevância aprendidos.',
    technical: 'A atenção por produto escalar escalado forma uma matriz QKᵀ normalizada e a multiplica por V.',
    example: 'Um resíduo mascarado pode usar informação de posições distantes da sequência.',
  },
  query: {
    name: 'Consulta',
    aliases: ['consultas', 'query', 'queries'],
    plain: 'O vetor de um token usado para pontuar a quais outros tokens prestar atenção.',
    technical: 'Produzido por uma projeção aprendida Q = XWQ na autoatenção.',
    example: 'Uma consulta é comparada com toda chave permitida por produto escalar.',
  },
  key: {
    name: 'Chave',
    aliases: ['chaves', 'key', 'keys'],
    plain: 'Um vetor com que a consulta se compara ao calcular as pontuações de atenção.',
    technical: 'K = XWK; a correspondência é aprendida e não corresponde necessariamente a uma propriedade interpretável.',
    example: 'A coluna da atenção identifica o token que fornece chave e valor.',
  },
  value: {
    name: 'Valor',
    aliases: ['valores', 'vetor de valor', 'value', 'values'],
    plain: 'A informação que um token contribui depois de calculados os pesos de atenção.',
    technical: 'V = XWV; a saída é uma soma ponderada dos vetores de valor.',
    example: 'Um token com peso 0,2 contribui com 0,2 vezes o vetor de valor dele.',
  },
  'attention-head': {
    name: 'Cabeça de atenção',
    aliases: ['cabeças de atenção', 'atenção de múltiplas cabeças', 'attention head', 'multi-head attention'],
    plain: 'Um conjunto de projeções de atenção dentro de uma camada de múltiplas cabeças.',
    technical: 'Cabeças diferentes têm projeções Q, K e V separadas; as saídas são concatenadas e projetadas.',
    example: 'Escolha a cabeça 1 e a cabeça 2 para ver padrões de atenção diferentes.',
  },
  mask: {
    name: 'Máscara',
    aliases: ['mascarado', 'mascaramento', 'máscara causal', 'mask', 'masked', 'causal mask'],
    plain: 'Um jeito de esconder a identidade de tokens ou bloquear o acesso a posições.',
    technical:
      'Um alvo de linguagem mascarada substitui ou modifica entradas escolhidas; uma máscara causal de atenção põe −∞ nas pontuações futuras. São usos diferentes de mascaramento.',
    example: '[MASK] esconde uma palavra; uma máscara causal bloqueia a atenção ao futuro.',
  },
  transformer: {
    name: 'Transformer',
    aliases: ['transformers'],
    plain: 'Uma arquitetura neural que junta atenção com processamento feed-forward.',
    technical: 'Inclui caminhos residuais, normalização e informação de posição; há variantes codificador, decodificador e codificador-decodificador.',
    example: 'O BERT é um Transformer no estilo codificador.',
  },
  encoder: {
    name: 'Codificador',
    aliases: ['codificadores', 'encoder'],
    plain: 'Um componente que converte uma entrada numa representação útil.',
    technical: 'Um codificador Transformer costuma usar autoatenção bidirecional para contextualizar os tokens de entrada.',
    example: 'O ESM-2 produz vetores que descrevem resíduos no contexto da sequência.',
  },
  decoder: {
    name: 'Decodificador',
    aliases: ['decodificadores', 'decoder'],
    plain: 'Um componente que produz ou modela saídas a partir de representações ou de tokens anteriores.',
    technical: 'Um decodificador Transformer causal bloqueia o contexto futuro. Sistemas codificador-decodificador também usam atenção cruzada.',
    example: 'Um decodificador no estilo GPT prevê o próximo token.',
  },
  residual: {
    name: 'Conexão residual',
    aliases: ['conexões residuais', 'residual', 'skip connection'],
    plain: 'Um atalho que soma uma representação anterior à versão transformada.',
    technical: 'Calcula x + f(x), o que ajuda o fluxo de informação e de gradiente por blocos empilhados.',
    example: 'Um Transformer soma a saída da atenção de volta à entrada dela.',
  },
  normalization: {
    name: 'Normalização',
    aliases: ['normalização de camada', 'normalizacao', 'layer normalization'],
    plain: 'Reescalar um conjunto de valores para manter o comportamento numérico sob controle.',
    technical: 'A normalização de camada padroniza os atributos dentro de um exemplo e aplica escala e deslocamento aprendidos.',
    example: 'Um Transformer normaliza as ativações ocultas em torno das subcamadas.',
  },
  bert: {
    name: 'BERT',
    aliases: [],
    plain: 'Um modelo que aprende representações de texto usando o contexto dos dois lados.',
    technical:
      'Representações Bidirecionais de Codificador a partir de Transformers; o treino original junta modelagem de linguagem mascarada e predição da próxima frase.',
    example: 'Prever o token escondido em "a proteína é [MASK]".',
  },
  llm: {
    name: 'Modelo de linguagem grande',
    aliases: ['LLM', 'LLMs', 'large language model'],
    plain: 'Um modelo de linguagem treinado em grande escala para modelar padrões de tokens.',
    technical: 'Não há limiar de parâmetros com que todos concordem; o objetivo de treino e a arquitetura continuam importando.',
    example: 'Um decodificador causal grande gera texto token a token.',
  },
  plm: {
    name: 'Modelo de linguagem de proteínas',
    aliases: ['pLM', 'pLMs', 'PLLM', 'protein language model'],
    plain: 'Um modelo de sequência que aprende padrões em sequências de aminoácidos.',
    technical: 'Costuma usar autossupervisão mascarada ou autorregressiva para aprender representações contextuais de resíduo.',
    example: 'ESM-2, ProtBERT e ProtT5 são modelos de linguagem de proteínas.',
  },
  'amino-acid': {
    name: 'Aminoácido',
    aliases: ['aminoácidos', 'resíduo', 'resíduos', 'aminoacido', 'amino acid', 'residue'],
    plain: 'Uma peça elementar de uma proteína; dentro de uma cadeia chama-se resíduo.',
    technical:
      'A notação padrão de sequência usa os 20 códigos comuns de uma letra; a biologia real também tem resíduos modificados e não padrão.',
    example: 'K indica lisina; G indica glicina.',
  },
  pooling: {
    name: 'Agregação',
    aliases: ['agregação por média', 'pooling', 'mean pooling'],
    plain: 'Combinar vários vetores num vetor de resumo.',
    technical: 'A agregação por média calcula a média dos vetores de resíduo válidos, excluindo preenchimento e tokens especiais.',
    example: 'Transformar embeddings por resíduo numa entrada única para um classificador de sequência.',
  },
  esm: {
    name: 'ESM-2',
    aliases: [],
    plain: 'Uma família de modelos de linguagem de proteínas que aprende de sequências de aminoácidos mascaradas.',
    technical: 'Fornece representações contextuais; o sistema ESMFold acrescenta uma arquitetura de enovelamento para prever estrutura.',
    example: 'Usar um embedding do ESM-2 como entrada de um classificador adiante.',
  },
  prott5: {
    name: 'ProtT5',
    aliases: [],
    plain: 'Um modelo de linguagem de proteínas baseado em T5, do projeto ProtTrans.',
    technical: 'O codificador dele gera embeddings por resíduo usados em predição adiante.',
    example: 'Agregar embeddings do ProtT5 para representar uma sequência inteira.',
  },
  protbert: {
    name: 'ProtBERT',
    aliases: [],
    plain: 'Um modelo de proteína baseado no aprendizado de sequência no estilo BERT.',
    technical: 'Parte do ProtTrans; aplica as ideias de modelagem mascarada a sequências de aminoácidos.',
    example: 'Uma ponte entre o codificador de texto do BERT e os modelos de sequência biológica.',
  },
  leakage: {
    name: 'Vazamento de dados',
    aliases: ['vazamento', 'leakage'],
    plain: 'Informação chega ao treino ou à seleção do modelo quando deveria estar reservada à avaliação final.',
    technical: 'Duplicatas, sobreposição de sequências homólogas ou pré-processamento ajustado em todos os dados inflam o desempenho relatado.',
    example: 'Proteínas muito aparentadas dos dois lados de uma divisão aleatória deixam a avaliação fácil demais.',
  },
  xor: {
    name: 'XOR',
    aliases: ['ou exclusivo'],
    plain: 'Uma regra lógica de duas entradas, verdadeira quando exatamente uma delas é verdadeira.',
    technical: 'Os casos positivos e negativos ocupam cantos opostos, então uma única fronteira linear não os separa.',
    example: 'O laboratório rotula um ponto como classe 1 quando as duas coordenadas têm sinais opostos.',
  },
};
