import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://madsondeluna.com"),
  title: "Madson Aragão: Portfolio",
  description:
    "Madson A. de Luna Aragão is a bioinformatician, health data scientist and PhD candidate in Bioinformatics (UFMG), working on multi-omics data analysis, machine learning and deep learning applied to structural biology, antimicrobial peptide discovery and drug design. Nextflow Ambassador, MBA student in Software Engineering (USP), specialist in Data Science and Analytics (PUC-Rio), MSc in Genetics and Molecular Biology (UFPE).",
  keywords: [
      "bioinformatician",
      "bioinformatics",
      "bioinformatics consultant",
      "bioinformatics specialist",
      "computational biology",
      "computational biologist",
      "data scientist",
      "health data scientist",
      "healthcare data science",
      "biomedical data science",
      "clinical bioinformatics",
      "biostatistics",
      "statistical genetics",
      "research and development analyst",
      "product manager",
      "technical product manager",
      "data-driven product management",
      "machine learning",
      "machine learning engineer",
      "deep learning",
      "artificial intelligence",
      "AI in healthcare",
      "AI in drug discovery",
      "generative AI",
      "large language models",
      "protein language models",
      "transformers",
      "neural networks",
      "MLOps",
      "predictive modeling",
      "feature engineering",
      "model interpretability",
      "XGBoost",
      "LightGBM",
      "scikit-learn",
      "PyTorch",
      "TensorFlow",
      "multi-omics",
      "multi-omics integration",
      "omics data analysis",
      "genomics",
      "functional genomics",
      "comparative genomics",
      "population genomics",
      "transcriptomics",
      "RNA-seq",
      "single-cell RNA-seq",
      "scRNA-seq",
      "proteomics",
      "peptidomics",
      "metabolomics",
      "epigenomics",
      "metagenomics",
      "microbiome analysis",
      "next-generation sequencing",
      "NGS",
      "whole genome sequencing",
      "whole exome sequencing",
      "long-read sequencing",
      "Nanopore",
      "Illumina",
      "variant calling",
      "variant annotation",
      "GWAS",
      "structural variants",
      "copy number variation",
      "gene expression analysis",
      "differential expression",
      "pathway enrichment",
      "functional annotation",
      "structural biology",
      "structural bioinformatics",
      "protein structure prediction",
      "AlphaFold",
      "molecular docking",
      "molecular dynamics",
      "PyMOL",
      "chemoinformatics",
      "cheminformatics",
      "drug discovery",
      "drug design",
      "peptide design",
      "de novo protein design",
      "antimicrobial peptides",
      "AMP prediction",
      "AMPidentifier",
      "antimicrobial resistance",
      "antibiotic resistance",
      "host defense peptides",
      "neoantigens",
      "immunoinformatics",
      "vaccine design",
      "dark genome",
      "biomarkers",
      "precision medicine",
      "personalized medicine",
      "digital health",
      "public health data",
      "translational research",
      "workflow automation",
      "reproducible research",
      "Nextflow",
      "Nextflow Ambassador",
      "nf-core",
      "Snakemake",
      "Docker",
      "Singularity",
      "containers",
      "high-performance computing",
      "HPC",
      "cloud computing",
      "AWS",
      "Google Cloud",
      "Microsoft Azure",
      "Linux",
      "Bash",
      "Python",
      "R",
      "SQL",
      "Git",
      "GitHub",
      "GitHub Actions",
      "CI/CD",
      "software engineering",
      "software architecture",
      "agile",
      "Scrum",
      "Kanban",
      "data engineering",
      "data governance",
      "data visualization",
      "dashboards",
      "Streamlit",
      "Flask",
      "NCBI",
      "Ensembl",
      "UniProt",
      "PDB",
      "KEGG",
      "biological databases",
      "PhD in Bioinformatics",
      "MBA in Software Engineering",
      "MSc Genetics and Molecular Biology",
      "BSc Biomedical Sciences",
      "UFMG",
      "UFPE",
      "USP",
      "PUC-Rio",
      "MIT Professional Education",
      "scientific writing",
      "peer review",
      "teaching bioinformatics",
      "Madson Aragao",
      "Madson Allan de Luna Aragao",
      "Luna-Aragao M",
      "bioinformata",
      "bioinformática",
      "biólogo computacional",
      "biologia computacional",
      "cientista de dados",
      "cientista de dados em saúde",
      "ciência de dados",
      "análise de dados biológicos",
      "bioestatística",
      "aprendizado de máquina",
      "aprendizado profundo",
      "inteligência artificial",
      "IA na saúde",
      "IA aplicada à descoberta de fármacos",
      "modelos generativos",
      "multiômicas",
      "análise multiômica",
      "genômica",
      "transcriptômica",
      "proteômica",
      "metabolômica",
      "metagenômica",
      "microbioma",
      "sequenciamento de nova geração",
      "análise de variantes",
      "expressão gênica",
      "anotação funcional",
      "biologia estrutural",
      "predição de estrutura de proteínas",
      "ancoragem molecular",
      "dinâmica molecular",
      "quimioinformática",
      "descoberta de fármacos",
      "desenho de peptídeos",
      "peptídeos antimicrobianos",
      "resistência antimicrobiana",
      "resistência a antibióticos",
      "neoantígenos",
      "genoma escuro",
      "biomarcadores",
      "medicina de precisão",
      "saúde digital",
      "fluxos de trabalho reprodutíveis",
      "computação de alto desempenho",
      "engenharia de software",
      "gestão de produtos",
      "gerente de produto",
      "governança de dados",
      "visualização de dados",
      "doutorado em bioinformática",
      "mestrado em genética e biologia molecular",
      "biomedicina",
      "patologia clínica",
      "pesquisa e desenvolvimento",
      "docência em bioinformática",
      "Madson Aragão",
      "Madson Allan de Luna Aragão",
      "bioinformático",
      "bioinformática",
      "biología computacional",
      "científico de datos",
      "ciencia de datos en salud",
      "aprendizaje automático",
      "aprendizaje profundo",
      "inteligencia artificial",
      "IA en salud",
      "modelos generativos",
      "multiómica",
      "análisis multiómico",
      "genómica",
      "transcriptómica",
      "proteómica",
      "metabolómica",
      "metagenómica",
      "microbioma",
      "secuenciación de nueva generación",
      "análisis de variantes",
      "expresión génica",
      "anotación funcional",
      "biología estructural",
      "predicción de estructura de proteínas",
      "acoplamiento molecular",
      "dinámica molecular",
      "quimioinformática",
      "descubrimiento de fármacos",
      "diseño de péptidos",
      "péptidos antimicrobianos",
      "resistencia antimicrobiana",
      "resistencia a antibióticos",
      "neoantígenos",
      "biomarcadores",
      "medicina de precisión",
      "salud digital",
      "flujos de trabajo reproducibles",
      "computación de alto rendimiento",
      "ingeniería de software",
      "gestión de productos",
      "gobernanza de datos",
      "visualización de datos",
      "doctorado en bioinformática",
      "investigación y desarrollo",
      "Madson Aragão"
  ],
  authors: [{ name: "Madson Allan de Luna Aragão", url: "https://madsondeluna.com" }],
  creator: "Madson Allan de Luna Aragão",
  robots: "index, follow",
  alternates: {
    canonical: "https://madsondeluna.com",
    languages: {
      "en-US": "https://madsondeluna.com/",
      "pt-BR": "https://madsondeluna.com/pt",
      es: "https://madsondeluna.com/es",
      "x-default": "https://madsondeluna.com/",
    },
  },
  openGraph: {
    type: "profile",
    url: "https://madsondeluna.com",
    siteName: "Madson Aragão",
    title: "Madson Aragão: Bioinformatician and Health Data Scientist",
    description:
      "Bioinformatician and health data scientist working on multi-omics, machine learning, deep learning and structural biology applied to antimicrobial peptide discovery and drug design.",
    locale: "en_US",
    alternateLocale: ["pt_BR", "es_ES"],
  },
  twitter: {
    card: "summary_large_image",
    site: "@madsondeluna",
    creator: "@madsondeluna",
    title: "Madson Aragão: Bioinformatician and Health Data Scientist",
    description:
      "Multi-omics, machine learning and structural biology applied to antimicrobial peptide discovery and drug design.",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable}`}
      suppressHydrationWarning
    >
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify({"@context": "https://schema.org", "@graph": [{"@type": "Person", "@id": "https://madsondeluna.com/#person", "name": "Madson Allan de Luna Aragão", "alternateName": ["Madson Aragão", "Madson de Luna Aragão", "Luna-Aragão, M. A.", "Madson A. de Luna Aragao"], "url": "https://madsondeluna.com", "email": "mailto:madsondeluna@gmail.com", "nationality": "Brazilian", "jobTitle": ["Bioinformatician", "Health Data Scientist", "Research and Development Analyst", "Product Manager", "PhD Candidate in Bioinformatics"], "description": "Bioinformatician and health data scientist working on multi-omics data analysis, machine learning and deep learning applied to structural biology, antimicrobial peptide discovery and drug design. Nextflow Ambassador and creator of AMPidentifier.", "image": "https://madsondeluna.com/assets/images/profile/me.jpeg", "sameAs": ["https://www.linkedin.com/in/madsonaragao/", "https://github.com/madsondeluna", "https://twitter.com/madsondeluna", "https://www.researchgate.net/profile/Madson-Aragao", "https://scholar.google.com.br/citations?user=GmHvOYsAAAAJ&hl=en", "https://www.ampidentifier.com/"], "knowsLanguage": [{"@type": "Language", "name": "Portuguese", "alternateName": "pt-BR"}, {"@type": "Language", "name": "English", "alternateName": "en"}, {"@type": "Language", "name": "Spanish", "alternateName": "es"}], "knowsAbout": ["bioinformatician", "bioinformatics", "bioinformatics consultant", "bioinformatics specialist", "computational biology", "computational biologist", "data scientist", "health data scientist", "healthcare data science", "biomedical data science", "clinical bioinformatics", "biostatistics", "statistical genetics", "research and development analyst", "product manager", "technical product manager", "data-driven product management", "machine learning", "machine learning engineer", "deep learning", "artificial intelligence", "AI in healthcare", "AI in drug discovery", "generative AI", "large language models", "protein language models", "transformers", "neural networks", "MLOps", "predictive modeling", "feature engineering", "model interpretability", "XGBoost", "LightGBM", "scikit-learn", "PyTorch", "TensorFlow", "multi-omics", "multi-omics integration", "omics data analysis", "genomics", "functional genomics", "comparative genomics", "population genomics", "transcriptomics", "RNA-seq", "single-cell RNA-seq", "scRNA-seq", "proteomics", "peptidomics", "metabolomics", "epigenomics", "metagenomics", "microbiome analysis", "next-generation sequencing", "NGS", "whole genome sequencing", "whole exome sequencing", "long-read sequencing", "Nanopore", "Illumina", "variant calling", "variant annotation", "GWAS", "structural variants", "copy number variation", "gene expression analysis", "differential expression", "pathway enrichment", "functional annotation", "structural biology", "structural bioinformatics", "protein structure prediction", "AlphaFold", "molecular docking", "molecular dynamics", "PyMOL", "chemoinformatics", "cheminformatics", "drug discovery", "drug design", "peptide design", "de novo protein design", "antimicrobial peptides", "AMP prediction", "AMPidentifier", "antimicrobial resistance", "antibiotic resistance", "host defense peptides", "neoantigens", "immunoinformatics", "vaccine design", "dark genome", "biomarkers", "precision medicine", "personalized medicine", "digital health", "public health data", "translational research", "workflow automation", "reproducible research", "Nextflow", "Nextflow Ambassador", "nf-core", "Snakemake", "Docker", "Singularity", "containers", "high-performance computing", "HPC", "cloud computing", "AWS", "Google Cloud", "Microsoft Azure", "Linux", "Bash", "Python", "R", "SQL", "Git", "GitHub", "GitHub Actions", "CI/CD", "software engineering", "software architecture", "agile", "Scrum", "Kanban", "data engineering", "data governance", "data visualization", "dashboards", "Streamlit", "Flask", "NCBI", "Ensembl", "UniProt", "PDB", "KEGG", "biological databases", "PhD in Bioinformatics", "MBA in Software Engineering", "MSc Genetics and Molecular Biology", "BSc Biomedical Sciences", "UFMG", "UFPE", "USP", "PUC-Rio", "MIT Professional Education", "scientific writing", "peer review", "teaching bioinformatics", "Madson Aragao", "Madson Allan de Luna Aragao", "Luna-Aragao M", "bioinformata", "bioinformática", "biólogo computacional", "biologia computacional", "cientista de dados", "cientista de dados em saúde", "ciência de dados", "análise de dados biológicos", "bioestatística", "aprendizado de máquina", "aprendizado profundo", "inteligência artificial", "IA na saúde", "IA aplicada à descoberta de fármacos", "modelos generativos", "multiômicas", "análise multiômica", "genômica", "transcriptômica", "proteômica", "metabolômica", "metagenômica", "microbioma", "sequenciamento de nova geração", "análise de variantes", "expressão gênica", "anotação funcional", "biologia estrutural", "predição de estrutura de proteínas", "ancoragem molecular", "dinâmica molecular", "quimioinformática", "descoberta de fármacos", "desenho de peptídeos", "peptídeos antimicrobianos", "resistência antimicrobiana", "resistência a antibióticos", "neoantígenos", "genoma escuro", "biomarcadores", "medicina de precisão", "saúde digital", "fluxos de trabalho reprodutíveis", "computação de alto desempenho", "engenharia de software", "gestão de produtos", "gerente de produto", "governança de dados", "visualização de dados", "doutorado em bioinformática", "mestrado em genética e biologia molecular", "biomedicina", "patologia clínica", "pesquisa e desenvolvimento", "docência em bioinformática", "Madson Aragão", "Madson Allan de Luna Aragão", "bioinformático", "bioinformática", "biología computacional", "científico de datos", "ciencia de datos en salud", "aprendizaje automático", "aprendizaje profundo", "inteligencia artificial", "IA en salud", "modelos generativos", "multiómica", "análisis multiómico", "genómica", "transcriptómica", "proteómica", "metabolómica", "metagenómica", "microbioma", "secuenciación de nueva generación", "análisis de variantes", "expresión génica", "anotación funcional", "biología estructural", "predicción de estructura de proteínas", "acoplamiento molecular", "dinámica molecular", "quimioinformática", "descubrimiento de fármacos", "diseño de péptidos", "péptidos antimicrobianos", "resistencia antimicrobiana", "resistencia a antibióticos", "neoantígenos", "biomarcadores", "medicina de precisión", "salud digital", "flujos de trabajo reproducibles", "computación de alto rendimiento", "ingeniería de software", "gestión de productos", "gobernanza de datos", "visualización de datos", "doctorado en bioinformática", "investigación y desarrollo", "Madson Aragão"], "alumniOf": [{"@type": "CollegeOrUniversity", "name": "Federal University of Minas Gerais (UFMG)", "url": "https://ufmg.br"}, {"@type": "CollegeOrUniversity", "name": "University of São Paulo (USP)", "url": "https://www5.usp.br"}, {"@type": "CollegeOrUniversity", "name": "Pontifical Catholic University of Rio de Janeiro (PUC-Rio)", "url": "https://www.puc-rio.br"}, {"@type": "CollegeOrUniversity", "name": "Federal University of Pernambuco (UFPE)", "url": "https://www.ufpe.br"}], "hasCredential": [{"@type": "EducationalOccupationalCredential", "credentialCategory": "degree", "educationalLevel": "Doctorate", "name": "PhD in Bioinformatics (ongoing)", "recognizedBy": {"@type": "CollegeOrUniversity", "name": "Federal University of Minas Gerais (UFMG)"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "degree", "educationalLevel": "Postgraduate", "name": "MBA in Software Engineering (ongoing)", "recognizedBy": {"@type": "CollegeOrUniversity", "name": "University of São Paulo (USP)"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "degree", "educationalLevel": "Postgraduate", "name": "Specialization in Data Science and Analytics", "recognizedBy": {"@type": "CollegeOrUniversity", "name": "Pontifical Catholic University of Rio de Janeiro (PUC-Rio)"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "degree", "educationalLevel": "Master's Degree", "name": "MSc in Genetics and Molecular Biology, emphasis in Bioinformatics", "recognizedBy": {"@type": "CollegeOrUniversity", "name": "Federal University of Pernambuco (UFPE)"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "degree", "educationalLevel": "Bachelor's Degree", "name": "BSc in Biomedical Sciences, emphasis in Clinical Pathology and Bioinformatics", "recognizedBy": {"@type": "CollegeOrUniversity", "name": "Federal University of Pernambuco (UFPE)"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Generative AI", "recognizedBy": {"@type": "Organization", "name": "Massachusetts Institute of Technology (MIT) Professional Education"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Advanced Gemini for Developers", "recognizedBy": {"@type": "Organization", "name": "Google DeepMind"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Microsoft Azure AI Essentials: Workloads and Machine Learning", "recognizedBy": {"@type": "Organization", "name": "Microsoft"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Career Essentials in Project Management", "recognizedBy": {"@type": "Organization", "name": "Microsoft"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Career Essentials in GitHub Professional Certificate", "recognizedBy": {"@type": "Organization", "name": "GitHub"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Agile Project Management Professional Certificate", "recognizedBy": {"@type": "Organization", "name": "Atlassian"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Project Management", "recognizedBy": {"@type": "Organization", "name": "Project Management Institute (PMI)"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Data-Driven Product Management", "recognizedBy": {"@type": "Organization", "name": "NASBA"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Requirements Engineering and Agile Product Management", "recognizedBy": {"@type": "Organization", "name": "PUC-Rio"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "The Data Science of Healthcare, Medicine, and Public Health", "recognizedBy": {"@type": "Organization", "name": "LinkedIn Learning"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Python Programming from Basic to Advanced", "recognizedBy": {"@type": "Organization", "name": "Udemy"}}, {"@type": "EducationalOccupationalCredential", "credentialCategory": "certificate", "name": "Bioinformatics with Python", "recognizedBy": {"@type": "Organization", "name": "Udemy"}}], "award": ["Next Generation Bioinformatician (NGB), X-Meeting 2025", "Travel Grant Award, ICTP-SAIFR School on Biological Physics and Biomolecular Simulations in the Machine Learning Era", "Travel Grant Award, AI for Protein Design (AI4PD), The Protein Society", "Young Geneticist Award of the Northeast (XXI ENGNE)", "Honorable Mention, Human and Forensic Genetics (CNPq/UFPE)", "Honorable Mention, Postgraduate Genetics Journey (UFPE)", "Best Poster Award, XIII Journey of the Genetics and Molecular Biology Program", "Certificate of Excellence in Peer Reviewing, Elsevier", "Highest admission score, MSc in Genetics and Molecular Biology (UFPE)", "Highest admission score, PhD in Bioinformatics (UFMG)"], "memberOf": [{"@type": "Organization", "name": "Nextflow Ambassador Program", "url": "https://www.nextflow.io/ambassadors.html"}], "subjectOf": [{"@type": "ScholarlyArticle", "name": "The Regulatory Army of Plant Defense: Transcription Factors in the War for Plant Immunity", "isPartOf": {"@type": "Periodical", "name": "International Journal of Molecular Sciences"}, "identifier": "https://doi.org/10.3390/ijms27167315", "url": "https://doi.org/10.3390/ijms27167315", "author": {"@id": "https://madsondeluna.com/#person"}}, {"@type": "ScholarlyArticle", "name": "Unveiling Three Functionally Diverse Isoforms of eIF4E in Cowpea Through a Multi-Omics Approach", "isPartOf": {"@type": "Periodical", "name": "Agronomy"}, "identifier": "https://doi.org/10.3390/agronomy16070766", "url": "https://doi.org/10.3390/agronomy16070766", "author": {"@id": "https://madsondeluna.com/#person"}}, {"@type": "ScholarlyArticle", "name": "Transposable elements: Functional aspects and applications as drivers of crop innovation", "isPartOf": {"@type": "Periodical", "name": "Crop Science"}, "identifier": "https://doi.org/10.1002/csc2.70257", "url": "https://doi.org/10.1002/csc2.70257", "author": {"@id": "https://madsondeluna.com/#person"}}, {"@type": "ScholarlyArticle", "name": "Deciphering Cowpea Resistance to Potyvirus: Assessment of eIF4E Gene Mutations and Their Impact on the eIF4E-VPg Protein Interaction", "isPartOf": {"@type": "Periodical", "name": "Viruses"}, "identifier": "https://doi.org/10.3390/v17081050", "url": "https://doi.org/10.3390/v17081050", "author": {"@id": "https://madsondeluna.com/#person"}}, {"@type": "ScholarlyArticle", "name": "Omics-driven bioinformatics for plant lectins discovery and functional annotation", "isPartOf": {"@type": "Periodical", "name": "International Journal of Biological Macromolecules"}, "identifier": "https://doi.org/10.1016/j.ijbiomac.2024.135511", "url": "https://doi.org/10.1016/j.ijbiomac.2024.135511", "author": {"@id": "https://madsondeluna.com/#person"}}, {"@type": "ScholarlyArticle", "name": "Association strength of E6 to E6AP/p53 complex correlates with HPV-mediated oncogenesis risk", "isPartOf": {"@type": "Periodical", "name": "Biopolymers"}, "identifier": "https://doi.org/10.1002/bip.23524", "url": "https://doi.org/10.1002/bip.23524", "author": {"@id": "https://madsondeluna.com/#person"}}, {"@type": "ScholarlyArticle", "name": "Approaches for Identification and Validation of Antimicrobial Compounds of Plant Origin", "isPartOf": {"@type": "Periodical", "name": "Eco-Friendly Biobased Products Used in Microbial Diseases, CRC Press"}, "identifier": "https://doi.org/10.1201/9781003243700", "url": "https://doi.org/10.1201/9781003243700", "author": {"@id": "https://madsondeluna.com/#person"}}]}, {"@type": "WebSite", "@id": "https://madsondeluna.com/#website", "url": "https://madsondeluna.com", "name": "Madson Aragão", "inLanguage": ["en", "pt-BR", "es"], "author": {"@id": "https://madsondeluna.com/#person"}, "publisher": {"@id": "https://madsondeluna.com/#person"}}, {"@type": "SoftwareApplication", "name": "AMPidentifier", "url": "https://www.ampidentifier.com/", "applicationCategory": "Scientific Software", "operatingSystem": "Web", "author": {"@id": "https://madsondeluna.com/#person"}, "description": "Ensemble machine learning toolkit for antimicrobial peptide prediction."}]}) }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `try{if(localStorage.getItem('theme')==='dark')document.documentElement.classList.add('dark')}catch(e){}`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
