'use client';
import {useId, type ReactNode} from 'react';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Tooltip,TooltipContent,TooltipTrigger} from '@/components/ui/tooltip';
import {MousePointer2} from 'lucide-react';
import {runLab} from '@/lib/museum/lab';
export function Control({label,value,onChange,min=0,max=1,step=.1,format,disabled=false}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number;format?:(v:number)=>string;disabled?:boolean}){const id=useId();return <div className="control"><div className="control-label"><span id={id}>{label}</span><output>{format?format(value):value.toFixed(2)}</output></div><Slider aria-labelledby={id} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])} disabled={disabled}/></div>}
export function Choice({label,value,onChange,items}:{label:string;value:string;onChange:(s:string)=>void;items:[string,string][]}){return <Tabs className="choice-tabs" value={value} onValueChange={onChange}><TabsList aria-label={label}>{items.map(([v,t])=><TabsTrigger value={v} key={v}>{t}</TabsTrigger>)}</TabsList></Tabs>}
export function Help({text,children}:{text:string;children:ReactNode}){return <Tooltip><TooltipTrigger asChild>{children}</TooltipTrigger><TooltipContent className="tooltip-copy">{text}</TooltipContent></Tooltip>}
export function Panel({title,hint='Hover or select to explore',children,inspector,footer}:{title:string;hint?:string;children:ReactNode;inspector:ReactNode;footer?:ReactNode}){return <section className="canvas-panel glass glass-frost lit lit-edge" data-lit aria-label={title}><div className="panel-top"><h2>{title}</h2><span className="hint"><MousePointer2 size={13}/>{hint}</span></div><div className="lab-layout"><div className="stage">{children}</div><aside className="inspector">{inspector}</aside></div><div className="panel-foot">{footer||<><span>Interactive exhibit</span><span>Explore with mouse, touch or keyboard</span></>}</div></section>}
export function Stats({items}:{items:[string,string][]}){return <div className="stat-row">{items.map(([value,label])=><div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>}
export function experiment<T>(body:unknown):Promise<T>{return new Promise((resolve,reject)=>setTimeout(()=>{try{resolve(runLab(body) as T)}catch(e){reject(e instanceof Error?e:new Error('The experiment failed. Try again.'))}},0))}
export function ErrorNote({error}:{error:string}){return error?<p className="error" role="alert">{error}</p>:null}
export function GraphGlyph({type=0}:{type?:number}){return <svg className="card-glyph" viewBox="0 0 230 60" aria-hidden="true">{type%3===0?<>{Array.from({length:22},(_,i)=><circle key={i} cx={12+i*9} cy={12+((i*19)%40)} r={2.5} fill={i%3?'var(--chart-2)':'var(--chart-1)'} opacity={.6}/>) }<path d="M15 52Q100 49 213 7" stroke="var(--chart-1)" strokeWidth="1.3" fill="none"/></>:type%3===1?<>{[0,1,2].flatMap(l=>[0,1,2,3].flatMap(j=>l<2?[0,1,2,3].map(k=><line key={`${l}-${j}-${k}`} x1={25+l*85} y1={8+j*14} x2={110+l*85} y2={8+k*14} stroke="var(--border)" strokeWidth=".7"/>):[]))}{[0,1,2].flatMap(l=>[0,1,2,3].map(j=><circle key={`${l}-${j}`} cx={25+l*85} cy={8+j*14} r={3.5} fill={l===1?'var(--chart-1)':'var(--chart-2)'}/>))}</>:<>{Array.from({length:7},(_,i)=><g key={i}><rect x={11+i*30} y={15} width={22} height={28} rx="3" stroke={i===3?'var(--chart-1)':'var(--border)'} fill={i===3?'color-mix(in oklab, var(--chart-1) 15%, transparent)':'none'}/><line x1={22+i*30} y1={9} x2={112} y2={3} stroke="var(--border)" strokeWidth=".8"/></g>)}</>}</svg>}
